### ISSUE TITLE
Map moved to the side

### ISSUE THREAD

**Issue by Noahheiz** [studio-minus/ppg-bugs-and-requests#495] opened 2021-11-12 21:18 UTC
**Describe the bug**
The map moved to the side
**Clearly describe how to reproduce the bug**
I dont know how this happend i played around whit the thermonuclear bomb on Blocks and then it lagged and the map moved a lot to the down left

**Mod list**
No

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version:Dont Know
 - GPU:Dont Know 
 - CPU:Dont know

**Additional notes**
Heres an immage of the bug
![image](https://user-images.githubusercontent.com/94200304/141535633-32e029c3-ffc7-487d-a443-213a6ec41e9c.png)

**Comment by mestiez** [comment] 2021-11-13 23:04
Duplicate of #1

**Closed by mestiez** 2021-11-13 23:04 UTC
Labels: bug
