### ISSUE TITLE
"Adding Aliens Instead of Animals"

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1651] opened 2022-07-08 17:24 UTC
**Feature description**
Time and time again, people have wanted Animals in People Playground even after Zooi rejected it multiple times. The truth is animals will never come to People Playground. To fill the void of not having animals, I'd like to suggest something different. Aliens.
For example, instead of having an alligator, we could have an alien inspired by an alligator, but without the cruelty associated with hurting an existing animal. Same thing for dogs, deer, horses, fish, and anything other animals.

**Feature purpose**
This will both allow more entities into the game and satisfy those who want animals. This suggestion can kill 2 birds with 1 stone, or, 2 small flying aliens with 1 stone. 

**Additional context**
"What did the aliens do wrong though?"
_**EVERYTHING!!!**_

**Comment by YourLocalPlonker** [comment] 2022-07-08 17:27
May I ask why you always put "" when you write a title

**Comment by DindinYT37** [comment] 2022-07-08 17:28
> May I ask why you always put "" when you write a title

I was about to ask that.

**Comment by DindinYT37** [comment] 2022-07-08 17:29
Related to #195 #1214

**Comment by SirAJ4895** [comment] 2022-07-08 17:38
> May I ask why you always put "" when you write a title

I just prefer to use quotes when I write titles, it's a force of habit

**Comment by SirAJ4895** [comment] 2022-07-08 17:41
> Related to #195 #1214

I feel like mine has slightly more clarity.

**Comment by DindinYT37** [comment] 2022-07-08 21:56
> > Related to #195 #1214
> 
> I feel like mine has slightly more clarity.

I didn't say yours is worse; I said it's related to them.

**Comment by mestiez** [comment] 2022-07-09 13:44
What aliens? Humanoid aliens? Suspiciously dog-like aliens? Closing until the issue is more specific.

**Closed by mestiez** 2022-07-09 13:44 UTC
Labels: feature-request

**Comment by DindinYT37** [comment] 2022-07-09 16:18
> What aliens? Humanoid aliens? Suspiciously dog-like aliens? Closing until the issue is more specific.

Well, "For example, instead of having an alligator, we could have an alien inspired by an alligator, but without the cruelty associated with hurting an existing animal. Same thing for dogs, deer, horses, fish, and anything other animals.".

**Comment by SirAJ4895** [comment] 2022-07-14 05:25
> What aliens? Humanoid aliens? Suspiciously dog-like aliens? Closing until the issue is more specific.

it explained it in my issue... I mean aliens that have animal qualities but don't have the cruelty involved with killing a real animal
