### ISSUE TITLE
Water flask

### ISSUE THREAD

**Issue by srabbs** [studio-minus/ppg-bugs-and-requests#2962] opened 2023-06-29 20:44 UTC
### Feature description

Flask that contains water and physically acts like any other liquid but it doesnt have an effect on humans.

### Feature purpose

The water flask contains water, so that the chemical possibilities of the game can extend or to extinguish fire. 

### Additional context

If it is possible, the water/liquid physics on the sea, hybrid, substructure and reactor a5 map can be changed so that they can drain, they can be connected to blood vessel wires for collection or they can be mixed with other liquids.

**Comment by DindinYT37** [comment] 2023-06-29 20:48
Duplicate of or related to:
* #359
* #413
* #597
* #792
* #844
* #849 
* #917
* #1002
* #1154
* #1182
* #1188
* #1189
* #1234
* #1244
* #1261
* #1262
* #1325 
* #1380
* #1791
* #2073
* #2562
* #2871

**Closed as completed** 2023-06-30 23:15 UTC
Labels: feature-request
