### ISSUE TITLE
Reverb bug

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#3229] opened 2023-10-21 16:08 UTC
### Describe the bug

Sometimes reverb just dissapearing.

### Clearly describe how to reproduce the bug

IDK, it seems to be randim, but it appears more frequently when: a lot of sounds in one moment(especially bullet impact/penetrating), loud sounds(explosion, sniper rifle).

One of guaranteed ways to get it is just fire grenade launcher at building for some time.

### Mod list
No

### Game version

1.27

### Operating System

Win10

**Comment by Afavertov** [comment] 2023-10-21 16:40
Firing 30mm at something also causes it.(i tried only metall objects)

**Comment by mestiez** [comment] 2023-10-21 17:09
Duplicate of #3188

**Closed as completed by mestiez** 2023-10-21 17:09 UTC
Labels: bug

**Comment by Afavertov** [comment] 2023-10-23 05:25
This was marked as duplicate, but original was closed by creator. I just want to know: are you going to fix it or not?
