### ISSUE TITLE
Anti-Phase Link

### ISSUE THREAD

**Issue by MauseLoch9000** [studio-minus/ppg-bugs-and-requests#1771] opened 2022-07-16 11:22 UTC
**Feature description**
Its basically a Phase Link connection, but when **Object A** is set to _disable collision_, it will _still_ collide with **Object B**, if both are connected with the **Anti-Phase Link**. 

**Feature purpose**
I was working on a blast-door system. But then I had the problem of the blast doors just getting blasted out of the door frame... Only freezing the frame could help, but if I did that, the other objects would also collide with the frame, which is indestructible; not just the door. I didnt find any solution or compromise. Thats why I make this request. With this new connection much more complex and advanced contraptions are possible.

**Additional context**
When _Detail View_ is enabled, the _Anti-Phase Link_ could look like the _Phase Link_, but with a different color, or a different shape. For example the _Phase Link_ is in a cross shape. The _Anti-Phase Link_ could be a Square.

**Comment by DindinYT37** [comment] 2022-07-16 11:25
Related to or Duplicate of:
* #118
* #555
* #758
* #870

**Comment by SirAJ4895** [comment] 2022-07-16 23:51
When the heck is Zooi gonna get around to this!?

**Comment by ATPGaming** [comment] 2022-10-09 03:11
> When the heck is Zooi gonna get around to this!?

never

**Closed** 2022-11-17 23:41 UTC
Labels: feature-request
