### ISSUE TITLE
Hit box of the human head is broken when its resized

### ISSUE THREAD

**Issue by sleepyham** [studio-minus/ppg-bugs-and-requests#1956] opened 2022-08-11 11:12 UTC
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by DindinYT37** [comment] 2022-08-11 11:29
Duplicate of #1328

**Comment by DindinYT37** [comment] 2022-08-11 11:29
Also, how about actually telling us about the bug next time?

**Comment by PossiblyRemember** [comment] 2022-08-11 19:20
hopefully _this one_ gets noticed

**Comment by mestiez** [comment] 2022-08-13 12:45
Ill explain

**Closed by mestiez** 2022-08-13 12:45 UTC
Labels: bug
