### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by StraightAdaptive** [studio-minus/ppg-bugs-and-requests#1653] opened 2022-07-08 21:10 UTC
A way to import pictures without the need of coding/messing with game files

**Comment by DindinYT37** [comment] 2022-07-08 21:58
Duplicate of #905

**Comment by SirAJ4895** [comment] 2022-07-09 06:34
You may want to close this suggestion since it has been marked as rejected on a similar suggestion.

**Closed** 2022-07-10 23:15 UTC
