### ISSUE TITLE
Clipboard history

### ISSUE THREAD

**Issue by koalakoalabanana** [studio-minus/ppg-bugs-and-requests#2873] opened 2023-04-29 17:53 UTC
### Feature description

A system where you can copy something without deleting the previous thing you copied (windows does this with Win+V)
Basically:
I copy thing A 
I then copy thing B
Which would make the clipboard contain just B, A having been lost forever
But with this feature I could open up a menu (with alt-V?) and move thing A to the top of the queue while preserving B.
So:
I copy A
I copy B
The clipboard queue is B, A (with B being spawned on the next paste)
But I can then open the clipboard menu and reorder to A, B

### Feature purpose

When I'm working on big stuff I use the copy function to keep a back-up of the contraption (as Save is inconvenient). But then if I copy a smaller subsystem to duplicate it, I lose that back-up, which is fine if I remember to copy the whole thing again, but I inevitably don't and lose a ton of progress.

**Comment by DindinYT37** [comment] 2023-04-29 21:13
Duplicate of #2740

**Comment by Squibard** [comment] 2023-04-30 02:02
> Duplicate of #2740

party pooper

**Closed as not planned** 2023-04-30 22:09 UTC
Labels: feature-request
