### ISSUE TITLE
Running animation/more refined walking animation.

### ISSUE THREAD

**Issue by howlzy** [studio-minus/ppg-bugs-and-requests#1979] opened 2022-08-17 05:34 UTC
A dynamic running animation would be great, and it's definitely possible in PPG with a little effort. Also the walking animation is decent but very stiff and may not work as intended at times. 

I think this could wonderful for PPG, would be really fun to fight off a horde of zombies sprinting at you.

Doesn't need to be to the extent of this, but Vector's running animation is very fluid and has the same 2D joints as a person in PPG. Could be a good reference: https://www.youtube.com/watch?v=RPb6n8fBHbo&ab_channel=NekkiVector

**Comment by DindinYT37** [comment] 2022-08-17 06:28
Duplicate of or Related to:
* #724 
* #1207 
* #1393 
* #1826 
* [card#77628361](https://github.com/studio-minus/ppg-bugs-and-requests/projects/1#card-77628361)

**Closed** 2022-08-20 19:46 UTC
Labels: feature-request
