### ISSUE TITLE
Can we do more things with water?

### ISSUE THREAD

**Issue by LeStinker** [studio-minus/ppg-bugs-and-requests#2562] opened 2022-12-18 22:14 UTC
### Feature description

Can we do stuff like store it, and have features for it, like water guns, oxygen tanks, etc

### Feature purpose

I think that a lot of people are annoyed by the fact that water is just there. It doesn't do anything except exist. Again, just a thought.

### Additional context

Water is fun in real life

**Comment by DindinYT37** [comment] 2022-12-19 12:41
Duplicate of or Related to:
* #359
* #412
* #413
* #423
* #541
* #597
* #610 
* #787
* #790
* #792
* #849 
* #1068
* #1085
* #1154
* #1182
* #1188
* #1189
* #1190 
* #1220
* #1234
* #1325 
* #1709 
* #1791
* #1916
* #2073
* #2530

**Comment by Squibard** [comment] 2022-12-25 13:51
oh my

**Comment by mestiez** [comment] 2022-12-31 01:52
this is very vague

**Closed by mestiez** 2022-12-31 01:52 UTC
Labels: feature-request

**Comment by ras09191** [comment] 2023-05-11 12:10
Thus contumely, the mind to sleep to sleep: perchance to dream: ay, the thousand natural shocks that sleep to sleep: perchance to dreams may come when we have, than fly to be: that the whips and scorns of outrageous fortune, or to takes, when we have shuffled off this mortal coil, must give us pause. There's the name of outrageous fortune, or not to be wish'd. To be, or not of? Thus contumely, the spurns that patient merit of thought, and by opposing end their currents turn awry, and thus the question
