### ISSUE TITLE
I really suggest that "Resizable Housing" have an option to move forwards or backwards

### ISSUE THREAD

**Issue by Langsvard** [studio-minus/ppg-bugs-and-requests#1801] opened 2022-07-19 10:32 UTC
It's more of a mechanic. Resizable housing would be cooler if it could move forwards or backwards in layers so that we could have more variety in our builds/ccontraptions.

**Comment by DindinYT37** [comment] 2022-07-19 10:34
Duplicate of or Related to:
* #834
* #838 
* #1057 
* #1223 
* #1227 
* #1515 
* #1684 

Also, please use the template.

**Comment by ATPGaming** [comment] 2022-09-04 08:08
you may want to close this since it was added with the beta

**Closed** 2022-12-31 02:26 UTC
Labels: feature-request
