### ISSUE TITLE
wheels cardiopulmonary bypass machine

### ISSUE THREAD

**Issue by xXGhostBoyXx** [studio-minus/ppg-bugs-and-requests#1581] opened 2022-07-01 13:09 UTC
**Describe the bug**
wheels of "cardiopulmonary bypass machine" during the feat fly higher with them

**Clearly describe how to reproduce the bug**

https://user-images.githubusercontent.com/88079829/176900417-44916bf9-cd48-477a-8390-6823774a9f69.mp4

**Mod list**
no.

**System info (please complete the following information)**
 - Operating system: windows 10 pro
 - Game version: 1.25 prewiew
 - GPU: geforce gt 730
 - CPU: amd ryzen 3 2200G

**Comment by DindinYT37** [comment] 2022-07-01 13:30
Duplicate of #1577

**Comment by xXGhostBoyXx** [comment] 2022-07-01 13:41
> Duplicate of #1577

ok ¯\_(ツ)_/¯

**Closed** 2022-07-01 13:42 UTC
Labels: bug
