### ISSUE TITLE
controllable  humans 

### ISSUE THREAD

**Issue by mingomango1234** [studio-minus/ppg-bugs-and-requests#2013] opened 2022-08-25 23:59 UTC
description 
new mechanic that lets you control humans also lets you make them fight each other/other things 

purpose 
the purpose is to make humans more interactive and make them feel like a living entity 
also to let you tell a story with epic fights between nations 

additional context 
be able to give humans enemy's or make them a part of a team also let you control them like in tabs

**Comment by DindinYT37** [comment] 2022-08-26 06:34
Basically duplicate of #1495

**Closed** 2022-08-29 10:30 UTC
Labels: feature-request
