### ISSUE TITLE
attachments for weapons

### ISSUE THREAD

**Issue by heartst0p** [studio-minus/ppg-bugs-and-requests#2062] opened 2022-09-02 19:39 UTC
attachments would be an awesome feature. suppressors, stocks, lasers, etc. maybe even larger mags with different ammo types.

**Comment by heartst0p** [comment] 2022-09-02 20:00
why is this a thumbs down

**Comment by DindinYT37** [comment] 2022-09-02 20:05
This is something that should be added by mods in my opinion.

**Comment by TeslaCoil9001** [comment] 2022-09-03 01:26
This is a duplicate of a feature that was rejected. I'd recommend closing this issue.
1623

**Comment by mestiez** [comment] 2022-12-31 02:07
this has been on the wishful thinking list and has since been implemented by aspa102

**Closed** 2022-12-31 02:07 UTC
Labels: feature-request
