### ISSUE TITLE
wind 

### ISSUE THREAD

**Issue by lawstinchaos** [studio-minus/ppg-bugs-and-requests#2302] opened 2022-10-28 01:27 UTC
**Feature description**
environment option that could set wind strength and direction .

**Feature purpose**
realism, fun , and more variety to weather effects.

**Additional context**
in addition to already existing weather settings it would make wonderful lightning and rain storms .

**Comment by DindinYT37** [comment] 2022-10-28 06:39
Duplicate of or Related to:
* #184
* #997
* #1014
* #1610 
* #1744

**Closed** 2022-12-31 02:31 UTC
Labels: feature-request
