### ISSUE TITLE
dynamite stick

### ISSUE THREAD

**Issue by SpanishPizza** [studio-minus/ppg-bugs-and-requests#1671] opened 2022-07-09 21:44 UTC
**Feature description**
It's like dynamite, but not bundled together, just stick dynamite.

**Feature purpose**
so that humans can hold and throw it

**Additional context**
No

**Comment by DindinYT37** [comment] 2022-07-09 23:05
Duplicate of #1177

**Closed** 2022-07-09 23:11 UTC
Labels: feature-request
