### ISSUE TITLE
speedometer

### ISSUE THREAD

**Issue by ifrost-source** [studio-minus/ppg-bugs-and-requests#1080] opened 2022-04-09 00:43 UTC
**Feature description**
It would be a small object like a the thermometer, which could be put on any vehicle (or moving object) to show how fast that object is going.

**Additional context**
N/A

**Comment by ppgplayer** [comment] 2022-04-09 02:37
I mean like, I could see this being useful for builds that need calculations. Like artillery or missiles to see how far they would go. I think this would be very useful.

**Comment by mestiez** [comment] 2022-04-10 00:02
Duplicate of #662

**Closed by mestiez** 2022-04-10 00:02 UTC
Labels: feature-request

**Comment by ifrost-source** [comment] 2022-04-10 02:47
oh sorry, should I delete this 🙁?
