### ISSUE TITLE
Menu sounds are affected by distant sound effects

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2352] opened 2022-11-05 16:39 UTC
**Describe the bug**
The menu buttons are affected by sound effects

**Clearly describe how to reproduce the bug**
Literally zoom out and go to the menu

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9944295/exported.game.debug.info.md)

**Additional notes**

https://user-images.githubusercontent.com/104321411/200131283-be212c38-e71a-4673-8536-7046f18d6dd6.mp4

**Comment by royalealbert27** [comment] 2022-11-09 11:38
i think that's intentional cuz of LOREEEE!!!!

**Comment by mestiez** [comment] 2022-12-31 02:21
Duplicate of #716

**Closed by mestiez** 2022-12-31 02:21 UTC
Labels: bug
