### ISSUE TITLE
Cycle counter

### ISSUE THREAD

**Issue by PZKPFW5** [studio-minus/ppg-bugs-and-requests#3208] opened 2023-10-15 04:01 UTC
### Feature description

An object that counts the number of signals of the same color, the player can set a goal, and when it is reached, the counter will emit all kinds (colors) of signals as many times as the player sets. The display should display the cycle and the set cycle (cycle at the moment/set cycle)

### Feature purpose

This will greatly help in the construction of mechanisms and their optimization

**Comment by mestiez** [comment] 2023-10-17 12:47
Duplicate of #3167

I think

**Closed as not planned by mestiez** 2023-10-17 12:47 UTC
Labels: feature-request
