### ISSUE TITLE
Bending

### ISSUE THREAD

**Issue by Qaz2137** [studio-minus/ppg-bugs-and-requests#2116] opened 2022-09-08 14:40 UTC
**Feature description**
Bending materials like for example metal pole

**Feature purpose**
i really want to make a turret for tank that i'm making but making a curve from couple of metal poles does not have enough strength.

**Comment by DindinYT37** [comment] 2022-09-08 14:51
Duplicate of or Related to:
* #655
* #659
* #1222 
* #1440 
* #1872 
* [<img src="https://user-images.githubusercontent.com/64973205/188866153-7e79e286-903c-4cbf-bcb7-8e82e8460a04.png" width="16px" height="16px"> "[MOD] Deformation"](https://steamcommunity.com/sharedfiles/filedetails/?id=2856121663)
* #2113 

*Something like this was requested just yesterday.*

**Closed** 2022-09-15 23:01 UTC
Labels: feature-request
