### ISSUE TITLE
Make reverse option for conveyor belt

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#1119] opened 2022-04-13 09:47 UTC
**Feature description**
A reverse option for conveyor belt that makes the conveyor belt move the other way

**Feature purpose**
it's helpful for vehicles so it can go backwards.

**Additional context**
zooi, why haven't you put this option when you made the conveyor belt???

**Comment by mestiez** [comment] 2022-04-13 09:48
Duplicate of #978

**Closed by mestiez** 2022-04-13 09:48 UTC
Labels: feature-request
