### ISSUE TITLE
Fixed resistor.

### ISSUE THREAD

**Issue by Drogo-man** [studio-minus/ppg-bugs-and-requests#1452] opened 2022-06-07 07:01 UTC
**Feature description**
A resistor that doesn't have a handle to change the resistance, but has a fixed number that you can change.

**Feature purpose**
The current resistor is outdated and doesn't work that well, also really unreliable.

**Additional context**

**Comment by DindinYT37** [comment] 2022-06-07 09:36
Duplicate of #1139

**Comment by DindinYT37** [comment] 2022-06-07 09:36
Reposts are still duplicates

**Closed** 2022-06-07 10:49 UTC
Labels: feature-request
