### ISSUE TITLE
Every weapon spawned by Q shoot random directions.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#384] opened 2021-10-31 16:35 UTC
Every weapon spawned by Q shoot random directions.

Spawn weapon by pressing Q and open fire.

No

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz
![изображение](https://user-images.githubusercontent.com/89081329/139593457-d9411b42-78f0-4faa-9bc4-e59881f4adb1.png)

**Comment by mestiez** [comment] 2021-10-31 18:02
Duplicate of #385

**Closed by mestiez** 2021-10-31 18:02 UTC
Labels: bug
