### ISSUE TITLE
Unbreakable option for all breakable objects

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2235] opened 2022-10-06 04:06 UTC
**Feature description**
Right now the breakable option is just for machinery so I think it should be for all objects that can be destroyed, crates, glass, TVs, pumpkins, ETC.

**Feature purpose**
This could help with buildings, videos, and contraptions

**Comment by DindinYT37** [comment] 2022-10-06 09:02
Duplicate of or Related to:
* #711
* #1555

**Closed** 2022-10-07 02:17 UTC
Labels: feature-request
