### ISSUE TITLE
Add Water Pressure

### ISSUE THREAD

**Issue by buggeboy** [studio-minus/ppg-bugs-and-requests#1180] opened 2022-04-25 15:28 UTC
Water pressure in the game, contraptions will begin to slowly collapse under pressure the deeper you go within the water. Humans will also be crushed under the force of the depths of the water. If a human is brought back up to the surface it will explode from the sudden change in pressure. (Eyes will pop out if you have expanded gore)   

I always love seeing these kind of small little additions, like how friction was added, so seeing more small lil additions like this would be a pleasant surprise.

**Comment by DindinYT37** [comment] 2022-04-25 16:18
Please keep the headers of the template when using it, as it provides more readability.

**Comment by DindinYT37** [comment] 2022-04-25 16:19
Duplicate of #243

**Closed** 2022-04-25 16:47 UTC
Labels: feature-request
