### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by Betryx** [studio-minus/ppg-bugs-and-requests#2701] opened 2023-01-24 18:41 UTC
### Feature description

Add an actuall fully working engine that can power or transfer power via the drive band.

### Feature purpose

it would be fun

**Comment by DindinYT37** [comment] 2023-01-27 22:51
Duplicate of or Related to:
* #1229
* #1256
* #1425

**Closed** 2023-01-29 14:07 UTC
Labels: feature-request

**Comment by username90001** [comment] 2023-02-06 17:45
> ### Feature description
> Add an actuall fully working engine that can power or transfer power via the drive band.
> 
> ### Feature purpose
> it would be fun
> 
> ### Additional context
> _No response_

u can do engine using electricity transformer detectors and boom boom or something like this
