### ISSUE TITLE
Layering System

### ISSUE THREAD

**Issue by Snogus41** [studio-minus/ppg-bugs-and-requests#1960] opened 2022-08-11 19:00 UTC
Maybe add a layering mechanic for the Resizable Housing, or just every item overall.

Itd be a thing in a context menu, thered be a button called "Layer" or something like that, it would then show a list of layers and what layer the item is on, you can add layers, but the default amount would be 10 layers for each item.

I think this would help building out a ton, so please take this into consideration.

**Comment by DindinYT37** [comment] 2022-08-11 19:12
Duplicate of or Related to:
* #834
* #838 
* #1057 
* #1223 
* #1227 
* #1515 
* #1684 
* #1801

Also, please use the template.

**Closed** 2022-12-31 02:26 UTC
Labels: feature-request
