### ISSUE TITLE
reverse phase links

### ISSUE THREAD

**Issue by legothenoob** [studio-minus/ppg-bugs-and-requests#870] opened 2022-03-17 13:11 UTC
**Feature description**

a new tool that works like the phase link, but instead of making two objects phase through eachother, it makes it so those two items are the only things that can collide with each other, with nothing else being able to collide with them

**Feature purpose**

its already possible to create a similar effect with regular phase links, except its an extreme headache to achieve because of how bloated the amount of phase links gets, with things like each bullet in a magazine needing half a dozen phase links to work (see images)

if you want to make it so only two objects collide with each other using phase links, you'd have to add a phase link to every object that is in their path, with some contraptions that isnt much of a problem, but for others, it can take hours

 reverse phase links would open up more possibilities for guns such as revolvers and high capacity magazines, and make already existing guns easier to make

**Additional context**

a gun with 3 double stack magazines, the game freezes for a couple seconds whenever you spawn it 
![phaselinkpain1](https://user-images.githubusercontent.com/101806405/158810417-25489b6c-479c-472f-9ce9-c85591035fc6.png)

an attempt at recreating the mars auto pistol, every single bullet needs 10 phase links connected to the gun
![phaselinkpain2](https://user-images.githubusercontent.com/101806405/158811020-3f524a15-f3e9-4a21-85ff-44bb7057d94b.png)

"Unreliable Revolver" by vkn164, with a single bullet having atleast two dozen phase links
![phaselinkpain3](https://user-images.githubusercontent.com/101806405/158814856-fdecc230-8414-4156-b693-5b290e120b38.png)

**Comment by DindinYT37** [comment] 2022-03-17 20:10
Duplicate of #118

**Closed** 2022-03-19 11:03 UTC
Labels: feature-request
