### ISSUE TITLE
Airtight hollow box, which doesn't flood.

### ISSUE THREAD

**Issue by urrone** [studio-minus/ppg-bugs-and-requests#1059] opened 2022-04-04 16:24 UTC
**Feature description**
Airtight spawnable hollow box, which when placed in any liquid on a map, doesn't just no-collide thru the water and "flood" the hollow box, it actually just removes the water effect and water background from the hollow part of the box, which preferably should be resizeable.

**Feature purpose**
The obvious purpose is of course to let humans live underwater and not suffocate. It can be used in many builds, machines, vehicles, etc.

**Comment by DindinYT37** [comment] 2022-04-04 20:45
Duplicate of #854

**Comment by urrone** [comment] 2022-04-04 21:19
**okay**

**Comment by WWWOWWWPL** [comment] 2022-04-08 16:45
> Duplicate of #854

i don't think so. this feature request is basically about a resizeable "water removing" block, whereas #854 suggests making all enclosed spaces completely airtight (i assume the walls would be made out of multiple parts)

**Comment by urrone** [comment] 2022-04-08 18:48
Duplicate or not it's a good feature, it's a shame that the game has the components to build underwater vehicles but can't be done since humans just drown without the use of a water-breathing syringe. Not to mention any ship's interior below the water level is inaccessible.

**Comment by DindinYT37** [comment] 2022-04-08 19:15
> > Duplicate of #854
> 
> i don't think so. this feature request is basically about a resizeable "water removing" block, whereas #854 suggests making all enclosed spaces completely airtight (i assume the walls would be made out of multiple parts)

It pretty much is the same thing though.

> Duplicate or not it's a good feature, it's a shame that the game has the components to build underwater vehicles but can't be done since humans just drown without the use of a water-breathing syringe. Not to mention any ship's interior below the water level is inaccessible.

I agree but then again, I'm also somewhat sure it has a way larger chance of being added than feature request for like, actual water physics.

**Comment by urrone** [comment] 2022-04-08 20:28
yeah cause the game dev is lazy and braindead lol

**Comment by DindinYT37** [comment] 2022-04-08 21:08
> yeah cause the game dev is lazy and braindead lol

No... quite literally because it would be way too CPU-intensive.

**Comment by urrone** [comment] 2022-04-09 08:29
Ehh I've seen successfully optimized water physics, let's not forget the game is 2D.

**Comment by DindinYT37** [comment] 2022-04-09 09:11
> Ehh I've seen successfully optimized water physics, let's not forget the game is 2D.

You should really inform yourself before saying things like this. What if zooi just doesn't want to add water physics? What if it'd take way too much time to optimize water physics to the point it's usable? Let's also not forget the whole game is basically based on mods, water physics + mods = not very good. Then again, as far as I have seen, People Playground is actually a 2D game made using Unity 3D.

**Comment by urrone** [comment] 2022-04-09 09:38
Inform my ass, what if zooi doesn't want to add water physics? Well crap, I guess no water physics. Too much time to optimize water particles colliding with each other in a 2D game? I mean it may be hard, but y' know u could also add settings for the water quality, so if some potato PC's can't handle it, then they can just lower the graphics, or even better, keep the option to return to the basic non-physical water. The game is based on mods, "water physics + mods = not very good", dude most mods are just added items and fewer actual changes to the fabric of the game. What's your point =.= Also this thread started off just a simple hollow box that removes water effects.

**Comment by urrone** [comment] 2022-04-09 09:46
> > Ehh I've seen successfully optimized water physics, let's not forget the game is 2D.
> 
> Then again, as far as I have seen, People Playground is actually a 2D game made using Unity 3D.

What? What kind of point is that, okay sure People Playground is made in Unity 3D, doesn't change the fact that the game is 2D.

**Comment by DindinYT37** [comment] 2022-04-09 10:23
> Inform my ass, what if zooi doesn't want to add water physics? Well crap, I guess no water physics. Too much time to optimize water particles colliding with each other in a 2D game? I mean it may be hard, but y' know u could also add settings for the water quality, so if some potato PC's can't handle it, then they can just lower the graphics, or even better, keep the option to return to the basic non-physical water. The game is based on mods, "water physics + mods = not very good", dude most mods are just added items and fewer are actual changes to the fabric of the game. What's your point =.= Also this thread started of just a simple hollow box that removes water effects.

You're really getting rude here, and meant with "take too much time to optimize" was that it would generally take too much time to get it right and working without any annoying bugs. The settings for water quality would also even further increase the time to be spent in development. And your point against my statement about the mods is only semi-true, many mods just add items, that's the point. Many mods are using hacky ways to create more interesting icons which could generally mess with the physics. Also it would break many mods since those new items wouldn't behave as intended or in the right way when in physic-based water.

**Comment by urrone** [comment] 2022-04-09 10:39
Bruh. Items have a basic border/shape, texture, and a few additions like the ability to stab/cut or shoot of a specific point of the item. The only thing that could mess with the water physics is the border/shape, which if it does, I mean how? if the object has the shape set that hows gonna react to the particles of the water. Also, your argument of "takes too much time" is like, okay. It does. Cool. Does ti mean it can't be done? No.

**Comment by urrone** [comment] 2022-04-09 10:44
> You're really getting rude here, and meant with "take too much time to optimize" was that it would generally take too much time to get it right and working without any annoying bugs.

Also, I'm pretty sure optimizing doesn't stand for fixing bugs/debugging, that's patching.

**Comment by DindinYT37** [comment] 2022-04-09 10:45
> > You're really getting rude here, and meant with "take too much time to optimize" was that it would generally take too much time to get it right and working without any annoying bugs.
> 
> Also, I'm pretty sure optimizing doesn't stand for fixing bugs/debugging, that's patching.

I said optimizing because it was the main point of what I meant, not because it was all of what I meant.

**Comment by DindinYT37** [comment] 2022-04-09 10:47
> Bruh. Items have a basic border/shape, texture, and a few additions like the ability to stab/cut or shoot of a specific point of the item. The only thing that could mess with the water physics is the border/shape, which if it does, I mean how? If the object has the shape set, that's how is gonna react to the particles of the water. Also, your argument of "takes too much time" is like, okay. It does. Cool. Does ti mean it can't be done? No.

It means it can't be done because People Playground's community was (in my opinion) close to dying, just because 1.23 took a bit longer. This community is not very patient when it comes to updates, if there are no mods to feed users with new content, or the user runs out of ideas, they basically quit until something new releases and/or may never come back.

**Comment by urrone** [comment] 2022-04-09 10:48
> 

Here's a question, how's any of that my problem?

**Comment by DindinYT37** [comment] 2022-04-09 10:49
> > 
> 
> Here's a question, how's any of that my problem?

And I quote: "yeah cause the game dev is lazy and braindead lol", you're being rude and close to toxicity because you think it's the developers fault. Of course it's not your problem, but that doesn't mean you have to be so egocentric as to think zooi will let his game community die for water physics.

**Comment by urrone** [comment] 2022-04-09 10:51
> > > You're really getting rude here, and meant with "take too much time to optimize" was that it would generally take too much time to get it right and working without any annoying bugs.
> > 
> > 
> > Also, I'm pretty sure optimizing doesn't stand for fixing bugs/debugging, that's patching.
> 
> I said optimizing because it was the main point of what I meant, not because it was all of what I meant.

You still used the word incorrectly. Optimizing is for setting the water physics to work for most lower-end PC's while debugging is just the process of making the feature.

**Comment by DindinYT37** [comment] 2022-04-09 10:52
> > > > You're really getting rude here, and meant with "take too much time to optimize" was that it would generally take too much time to get it right and working without any annoying bugs.
> > > 
> > > 
> > > Also, I'm pretty sure optimizing doesn't stand for fixing bugs/debugging, that's patching.
> > 
> > 
> > I said optimizing because it was the main point of what I meant, not because it was all of what I meant.
> 
> You still used the word incorrectly. Optimizing is for setting the water physics to work for most lower-end PC's while debugging is just the process of making the feature.

I know what optimizing it, but that's just the way how I talk. If I'm addressing a large topic, I usually mention the major / biggest part of the topic to address the large topic if it has no name.

**Comment by urrone** [comment] 2022-04-09 10:55
Stop stretching shit. God damn, the reputation of the game ISN'T my business. You still used the word incorrectly idc.

**Comment by urrone** [comment] 2022-04-09 10:56
> And I quote: "yeah cause the game dev is lazy and braindead lol", you're being rude and close to toxicity because you think it's the developers fault.

What?

**Comment by DindinYT37** [comment] 2022-04-09 10:56
> Stop stretching shit. God damn, the reputation of the game ISN'T my business. You still used the word incorrectly idc.

If it's not your business, then stop caring and get off GitHub since it is the Developer's business and you're suggesting to the Developer here. Also, why are you still stuck on me using a word wrong even though I have already explained to you what I meant several times?

**Comment by urrone** [comment] 2022-04-09 10:56
Who am I blaming here? Wtf are u talking about.

**Comment by DindinYT37** [comment] 2022-04-09 10:57
> Who am I blaming here? Wtf are u talking about.

https://github.com/studio-minus/ppg-bugs-and-requests/issues/1059#issuecomment-1093325959

**Comment by urrone** [comment] 2022-04-09 10:58
Yeah umm .. let me repeat myself, how's the game's reputation my business? Dude yes I called the dev braindead and lazy cause the game is dying.

**Comment by DindinYT37** [comment] 2022-04-09 10:59
> Yeah umm .. let me repeat myself, how's the game's reputation my business? Dude yes I called the dev braindead and lazy cause the game is dying.

Let me repeat myself: https://github.com/studio-minus/ppg-bugs-and-requests/issues/1059#issuecomment-1093901713

**Comment by urrone** [comment] 2022-04-09 11:00
> If it's not your business, then stop caring and get off GitHub since it is the Developer's business and you're suggesting to the Developer here. Also, why are you still stuck on me using a word wrong even though I have already explained to you what I meant several times?

xD What??

**Comment by DindinYT37** [comment] 2022-04-09 11:00
> > If it's not your business, then stop caring and get off GitHub since it is the Developer's business and you're suggesting to the Developer here. Also, why are you still stuck on me using a word wrong even though I have already explained to you what I meant several times?
> 
> xD What??

Are you trying to save yourself by making it seem ridiculous now?

**Comment by urrone** [comment] 2022-04-09 11:01
I'm a player suggesting a feature. Wdym I'm suggesting to be a dev here?

**Comment by DindinYT37** [comment] 2022-04-09 11:01
> I'm a player suggesting a feature. Wdym I'm suggesting to be a dev here?

You're suggesting **to the** Developer, read it again.

**Comment by urrone** [comment] 2022-04-09 11:02
Alright, I'm still confused, so cause I called the dev braindead and lazy I'm making the game's reputation my problem?

**Comment by urrone** [comment] 2022-04-09 11:04
> I'm a player suggesting a feature. Wdym I'm suggesting to be a dev here?

Please.

**Comment by DindinYT37** [comment] 2022-04-09 11:04
> Alright, I'm still confused, so cause I called the dev braindead and lazy I'm making the game's reputation my problem?

Not what I said. If the game's reputation is not your problem, to the degree that you don't even think about using common sense - you don't have the right to suggest anything if you're just here to tell us you don't care about the game's community and insult the developer.

**Comment by DindinYT37** [comment] 2022-04-09 11:05
> > I'm a player suggesting a feature.
> 
> Please.

Let me repeat myself, **again**: https://github.com/studio-minus/ppg-bugs-and-requests/issues/1059#issuecomment-1093907255

**Comment by urrone** [comment] 2022-04-09 11:05
=.=

**Comment by urrone** [comment] 2022-04-09 11:05
> you don't have the right to suggest anything if you're just here to tell us you don't care about the game's community and insult the developer.

Umm, yes I do?

**Comment by urrone** [comment] 2022-04-09 11:06
Cause I care about the game itself .. y' know.

**Comment by DindinYT37** [comment] 2022-04-09 11:07
It seems you simply don't get what I mean even after saying it several times, so I'm gonna give up trying to talk to a wall.

**Comment by urrone** [comment] 2022-04-09 11:11
> If it's not your business, then stop caring and get off GitHub since it is the Developer's business and you're suggesting to the Developer here. 

Okay, so because I called the dev braindead and lazy, because I care about the gameplay, and because I'm suggesting a feature **I'm** making the game's reputation my problem?

**Comment by urrone** [comment] 2022-04-09 11:14
Also congrats on wasting your own time and mine as well on your dum argument, 40 comments cause you're such a warrior for the poor dev.

**Comment by urrone** [comment] 2022-04-09 11:17
> Of course it's not your problem, but that doesn't mean you have to be so egoistical as to think zooi will let his game community die for water physics just to keep you.

Dude this thread started of a hollow box, that removes water effects.

**Comment by urrone** [comment] 2022-04-09 11:29
> You're really getting rude here, 

Sorry mom, won't say "ass" again.

**Comment by WWWOWWWPL** [comment] 2022-04-09 11:53
Bruh

**Comment by urrone** [comment] 2022-04-09 11:57
lol @DindinYT37 is malding, crawling cause I don't give fucks abt the state of the game.

**Comment by DindinYT37** [comment] 2022-04-09 12:00
> lol @DindinYT37 is malding, crawling cause I don't give fucks abt the state of the games fan base.

Didn't you say I'm the one wasting my time while you're here spouting nonsense?

**Comment by urrone** [comment] 2022-04-09 12:08
You also wasted my time, cause you assume everyone suggesting something just has to give a fuck about the reputation of the game, the time the feature needs to get created, etc.

**Comment by ppgplayer** [comment] 2022-04-09 14:06
din din mental breakdown moment

**Closed** 2022-04-10 12:07 UTC
Labels: feature-request
