### ISSUE TITLE
Phase link but different

### ISSUE THREAD

**Issue by LijmPistool** [studio-minus/ppg-bugs-and-requests#758] opened 2022-02-28 14:08 UTC
**Feature description**
Phase link but different (I don't know how to name it)

**Feature purpose**
Right now we have phase link, you can connect 2 objects to a phase link and they will phase through eachother.
But this got me thinking, wouldn't it be nice if we had a phase link that only allows the 2 connected objects to have collision and that it disables the collision for other objects. I don't know how to explain properly but the phase link we have now allows 2 objects to phase through each other and the feature that I want won't allow the 2 connected objects to phase to each other but other objects that **aren't** connected **can** pass through

**Additional context**
n.v.t.

**Comment by UniDuki** [comment] 2022-02-28 14:28
Duplicate of #118
I called it an "Anti Phase Link"

**Comment by LijmPistool** [comment] 2022-02-28 16:29
> Duplicate of #118 I called it an "Anti Phase Link"

oh oops, I couldn't find it. sorry

**Comment by D3stStrut** [comment] 2022-03-01 11:03
> Duplicate of #118 I called it an "Anti Phase Link"

bro you are such a nerd

**Closed** 2022-03-07 09:19 UTC
Labels: feature-request
