### ISSUE TITLE
error with saving contraptions

### ISSUE THREAD

**Issue by TailsOfBeasts** [studio-minus/ppg-bugs-and-requests#2356] opened 2022-11-07 06:33 UTC
**Describe the bug**
whenever I download mods for example like the https://steamcommunity.com/sharedfiles/filedetails/?id=2816888361 mod and I make a contraption out of it and try to save it what happens is that on the bottom right it says "saved with errors"

**Clearly describe how to reproduce the bug**
now this only works with some mods but download any mod that includes guns and armor make something out of that mod try to save it and boom you have you error 

**Mod list**
these are the ones im experiencing problems with at the moment
https://steamcommunity.com/sharedfiles/filedetails/?id=2816888361
https://steamcommunity.com/sharedfiles/filedetails/?id=2784935218

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: current
 - GPU: GTX 1650 super
 - CPU: amd ryzen 5 3600 6 core

**Additional notes**
I dont know if this is a bug or something that happens sometimes because I have been playing people playground for a very long time now so if its not a bug describe how this happens

**Comment by DindinYT37** [comment] 2022-11-07 13:02
Duplicate of #2355

**Comment by Drogo-man** [comment] 2022-11-07 13:14
That is a mod problem

**Comment by TailsOfBeasts** [comment] 2022-11-07 20:00
so is there any possible fixes or do I just gotta deal with it and cry

**Comment by DindinYT37** [comment] 2022-11-07 20:11
> so is there any possible fixes or do I just gotta deal with it and cry

You could try finding what modded object causes the issue, and then perhaps remove that mod.

**Comment by TailsOfBeasts** [comment] 2022-11-07 20:20
well I already did its the armor and the guns but I need them both for what im doing so yeah

**Comment by Drogo-man** [comment] 2022-11-07 20:24
Just cry, best bet. Or cry to the mod maker.

**Comment by TailsOfBeasts** [comment] 2022-11-07 20:28
ima turn into the worst steam user thank you for your help

**Closed** 2022-11-07 20:29 UTC
Labels: bug

**Comment by DindinYT37** [comment] 2022-11-07 20:44
> well I already did its the armor and the guns but I need them both for what im doing so yeah

Armor never really worked well with saving.
