### ISSUE TITLE
Possibility to reload weapons with different types of bullets

### ISSUE THREAD

**Issue by henriquelmeeee** [studio-minus/ppg-bugs-and-requests#2374] opened 2022-11-10 10:50 UTC
**Feature description**
Possibility to reload weapons with different types of bullets

**Feature purpose**
This will be interesting because you'll be able to test different bullets in different weapons, simulating their impact, force, amount of gunpowder, etc.

**Comment by DindinYT37** [comment] 2022-11-10 11:01
Duplicate of or Related to:
* #1594 
* #1672

**Comment by Drogo-man** [comment] 2022-11-10 12:34
It's not a duplicate of any of these.

**Comment by DindinYT37** [comment] 2022-11-10 13:05
> It's not a duplicate of any of these.

It says "Duplicate of **or** Related to", not "Duplicate of **and** Related to".

**Comment by bibbybabby** [comment] 2022-11-10 14:01
That's choosing different bullets, not reloading as a whole

**Comment by DindinYT37** [comment] 2022-11-10 19:34
> That's choosing different bullets, not reloading as a whole

Ammo is related to Ammo.

**Comment by bibbybabby** [comment] 2022-11-10 19:46
> > That's choosing different bullets, not reloading as a whole
> 
> Ammo is related to Ammo.

What the request meant is different ammunition, not reloading. That's like saying that zebras and mice are the same because they are both mammals

**Comment by DindinYT37** [comment] 2022-11-10 20:01
> > > That's choosing different bullets, not reloading as a whole
> > 
> > 
> > Ammo is related to Ammo.
> 
> What the request meant is different ammunition, not reloading. That's like saying that zebras and mice are the same because they are both mammals

They both fall under the mammal category, then, don't they?

**Comment by bibbybabby** [comment] 2022-11-10 20:04
> > > > That's choosing different bullets, not reloading as a whole
> > > 
> > > 
> > > Ammo is related to Ammo.
> > 
> > 
> > What the request meant is different ammunition, not reloading. That's like saying that zebras and mice are the same because they are both mammals
> 
> They both fall under the mammal category, then, don't they?

We're going a bit off topic, what I'm trying to say is that weapon reloading and ammunition changing is different 

_And before you hit me with the "but it says reloading!" In this context it just means loading different ammo, not actually reloading_

**Comment by DindinYT37** [comment] 2022-11-10 20:06
> > > > > That's choosing different bullets, not reloading as a whole
> > > > 
> > > > 
> > > > Ammo is related to Ammo.
> > > 
> > > 
> > > What the request meant is different ammunition, not reloading. That's like saying that zebras and mice are the same because they are both mammals
> > 
> > 
> > They both fall under the mammal category, then, don't they?
> 
> We're going a bit off topic, what I'm trying to say is that weapon reloading and ammunition changing is different
> 
> _And before you hit me with the "but it says reloading!" In this context it just means loading different ammo, not actually reloading_

It's still both about ammunition.

**Comment by bibbybabby** [comment] 2022-11-10 20:10
> It's still both about ammunition.

no offense but here lemme just do whats called "mini-modding" by some individuals

- #2071
- #1319
- #582
- #361

I think these fit more than your issues that you wrote

**Comment by DindinYT37** [comment] 2022-11-10 20:44
> > It's still both about ammunition.
> 
> no offense but here lemme just do whats called "mini-modding" by some individuals
> 
> * [load slug #2071](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2071)
> * [Grenade launcher rounds #1319](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1319)
> * [White phosphorus munitions. #582](https://github.com/studio-minus/ppg-bugs-and-requests/issues/582)
> * [Ammo types. #361](https://github.com/studio-minus/ppg-bugs-and-requests/issues/361)
> 
> I think these fit more than your issues that you wrote

Actually knew about #361, but couldn't find the issue.

**Closed** 2022-11-12 16:00 UTC
Labels: feature-request
