### ISSUE TITLE
Allow mods to be reloaded in the game itself

### ISSUE THREAD

**Issue by Dawid23-Gamer** [studio-minus/ppg-bugs-and-requests#2091] opened 2022-09-04 16:42 UTC
**Feature description**
Allow mods (or at least mods that the player owns) to be manually reloaded directly from the 'mod' menu.

**Feature purpose**
It would make making a mod (e.g. tweaking some specific values) easier because you wouldn't have to reload the game every time you change something.

**Additional context**
There is none, the idea is rather straight forward

**Comment by DindinYT37** [comment] 2022-09-04 18:35
Duplicate of or Related to:
* #589
* #605 
* #694
* #1072 
* #1173 
* #1192 
* #1794 
* #1957
* #1998

*Note that basically what you requested here was rejected several times before, so this will probably also be rejected but I didn't expect anything more from you in the first place.*

**Comment by Dawid23-Gamer** [comment] 2022-09-04 19:19
I mean idk how I did not expect the fact it was suggested before

**Closed** 2022-09-04 21:29 UTC
Labels: feature-request
