### ISSUE TITLE
When defibrillator handles are connected to something with wire/rope/string.

### ISSUE THREAD

**Issue by xpdatabase11** [studio-minus/ppg-bugs-and-requests#145] opened 2021-08-24 09:05 UTC
**Describe the bug**
When you copy paste a defibrillator with its handles connected to something else, with any type of wire/rope/string. The rope ends up connected from the defibrillator to the handles, like the original cables that come with the original defibrillator.

**Clearly describe how to reproduce the bug**
1: Spawn Defibrillator
2: Attach the handles to the background or another object with a wire/rope/string.
3: Copy Paste it
4: Final Result

**Mod list**
No mods

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21.3 (64bit)
 - GPU: AMD Radeon Rx580
 - CPU: AMD Ryzen 7 2700x (8core)

**Screen Shot**
![Defibulator Bug](https://user-images.githubusercontent.com/37987479/130589317-261c610d-3ae7-4a51-8bec-b6d1e2a9ca3c.png)

**Comment by mestiez** [comment] 2021-08-24 09:30
Duplicate of #14

**Closed by mestiez** 2021-08-24 09:30 UTC
Labels: bug
