### ISSUE TITLE
Brain Chip

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2318] opened 2022-10-30 18:07 UTC
**Feature description**
Add a little metal device that can be wired into a brain-dead or headless human that acts as an artificial to make him function again

**Feature purpose**
So we can have headless humans and also bring back humans who's brain no longer functions

**Comment by DindinYT37** [comment] 2022-10-30 18:55
What you requested is a brain chip, not an artificial head. So, I very much doubt it would be able to have headless humans using it.

**Comment by DindinYT37** [comment] 2022-10-30 18:57
Duplicate of or Related to:
* #2305

**Closed** 2022-10-30 19:03 UTC
Labels: feature-request
