### ISSUE TITLE
Collision Gate

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2321] opened 2022-10-30 19:03 UTC
**Feature description**
Add a wall that when activated, will toggle collision

**Feature purpose**
This could be good for doors or contraptions

**Comment by DindinYT37** [comment] 2022-10-30 19:08
Duplicate of or Related to:
* #1200
* #1607 
* #1813
* #2226 

*The Door is also just an object that toggles collision on activation, which is why I included it.*

**Closed** 2022-10-30 19:11 UTC
Labels: feature-request
