### ISSUE TITLE
new gore

### ISSUE THREAD

**Issue by venixals** [studio-minus/ppg-bugs-and-requests#2211] opened 2022-09-28 20:16 UTC
when you shoot someone in the eyes, their eyeballs pop out, when you cut off or shoot someones lower torso/waist, intestines fall down 

(with physics) maybe if u bash someone in the head enough times you can see their skull or brain.

**Comment by DindinYT37** [comment] 2022-09-28 20:40
Duplicate of #2209

**Comment by DindinYT37** [comment] 2022-09-28 20:41
You can already see the skull if you get through to the bone layer of the head. Also, please use the template and don't just rephrase the same feature request you posted already.

**Comment by bibbybabby** [comment] 2022-09-28 23:30
This sounds awfully a lot like expanded gore

**Comment by YourLocalPlonker** [comment] 2022-09-30 14:43
> This sounds awfully a lot like expanded gore

this is basically expanded gore but it got removed for a reason

**Comment by DindinYT37** [comment] 2022-09-30 15:02
@bibbybabby @YourLocalPlonker in case you wanna know, he requested this about 30 seconds after zooi closed #2209 (which he also requested) because it was also just expanded gore.

**Comment by bibbybabby** [comment] 2022-09-30 16:00
> @bibbybabby @YourLocalPlonker in case you wanna know, he requested this about 30 seconds after zooi closed #2209 (which he also requested) because it was also just expanded gore.

Do you know the definition of insanity?

**Comment by DindinYT37** [comment] 2022-09-30 16:05
> > @bibbybabby @YourLocalPlonker in case you wanna know, he requested this about 30 seconds after zooi closed #2209 (which he also requested) because it was also just expanded gore.
> 
> Do you know the definition of insanity?

Yes, I do. Though I don't quite get what you're trying to tell me.

**Comment by bibbybabby** [comment] 2022-09-30 16:32
> > > @bibbybabby @YourLocalPlonker in case you wanna know, he requested this about 30 seconds after zooi closed #2209 (which he also requested) because it was also just expanded gore.
> > 
> > 
> > Do you know the definition of insanity?
> 
> Yes, I do. Though I don't quite get what you're trying to tell me. _Perhaps, are you trying to inform me of the fact he said he's a psychopath in #2209?_

no i meant far cry 3 reference and the psychopath thing is a joke

**Closed** 2022-12-31 01:59 UTC
Labels: feature-request
