### ISSUE TITLE
Map Elements can be glitched out of place

### ISSUE THREAD

**Issue by Ballisticpat** [studio-minus/ppg-bugs-and-requests#1518] opened 2022-06-22 23:38 UTC
**Describe the bug**
Spawning complex contraptions inside of a ground element causes extreme lag, and when the contraption is undone some ground elements have been shifted to seemingly random positions. Image: 
![20220622180116_1](https://user-images.githubusercontent.com/108034789/175171745-4f0665a9-63d1-4cf3-8bef-04a2a1964390.jpg)
What looks like ground at the bottom has no collision.

**Clearly describe how to reproduce the bug**
Spawn a complex contraption inside of a ground element. If the computer lags hit z, the screen may or may not black out and the ground element you spawned the contraption in will have moved.
link to the contraption I used: https://steamcommunity.com/sharedfiles/filedetails/?id=2824601776

**Instance Info**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8962364/exported.game.debug.info.md)

**Additional notes**
Physics is set to continuous.

On the map "Blocks" I could recreate this, but when I did so a siren sounded, the lights shut off, and the map closed. So this could be intentional, however this did not happen when I performed the glitch in Abyss.

**Comment by DindinYT37** [comment] 2022-06-23 05:10
Basically duplicate of #1

**Closed** 2022-06-23 11:21 UTC
Labels: bug
