### ISSUE TITLE
add cutting!

### ISSUE THREAD

**Issue by YourLocalGDNoob** [studio-minus/ppg-bugs-and-requests#2820] opened 2023-03-26 20:58 UTC
### Feature description

add a feature and maybe a setting which allows for sharp objects to cut humans

### Feature purpose

more gore, stabbing exists, but it doesnt give the same feel

**Comment by DindinYT37** [comment] 2023-03-27 10:50
Duplicate of or Related to:
* #168
* #808
* #1432
* #1792
* #2774

**Closed as completed** 2023-04-18 21:33 UTC
Labels: feature-request
