### ISSUE TITLE
editing backround

### ISSUE THREAD

**Issue by crystorgic** [studio-minus/ppg-bugs-and-requests#2436] opened 2022-11-19 09:31 UTC
### Feature description

you can change the background tiles by right clicking on nothing and have an option called "change background". Once you clicked on the option you will be prompted with background options like city, forest, mountains, , etc. You can get more backgrounds from downloading from the workshop or importing pictures from your device. The background should also play a different ambient sounds to make sense with the background

### Feature purpose

having the option to change backgrounds would make the map look better and overall more alive, it is also a opportunity to make more interesting videos by having the background match the situation.

**Comment by bibbybabby** [comment] 2022-11-19 14:28
Duplicate of #1972

_also, if people could upload pictures to the workshop it would turn into nsfw hell_

**Comment by ATPGaming** [comment] 2022-11-19 14:58
> Duplicate of #1972
> 
> _also, if people could upload pictures to the workshop it would turn into nsfw hell_

What does nsfw mean?

**Comment by TeslaCoil9001** [comment] 2022-11-19 14:59
> > Duplicate of #1972
> > _also, if people could upload pictures to the workshop it would turn into nsfw hell_
> 
> What does nsfw mean?

Oh god you're too innocent for People Playground

**Comment by DindinYT37** [comment] 2022-11-19 16:00
> > Duplicate of #1972
> > _also, if people could upload pictures to the workshop it would turn into nsfw hell_
> 
> What does nsfw mean?

May I remind you of [this part in the GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#:~:text=You%20must%20be%20age%2013%20or%20older.%20While%20we%20are%20thrilled%20to%20see%20brilliant%20young%20coders%20get%20excited%20by%20learning%20to%20program%2C%20we%20must%20comply%20with%20United%20States%20law.%20GitHub%20does%20not%20target%20our%20Service%20to%20children%20under%2013%2C%20and%20we%20do%20not%20permit%20any%20Users%20under%2013%20on%20our%20Service.)?

**Comment by ATPGaming** [comment] 2022-11-19 17:38
> > > Duplicate of #1972
> > > _also, if people could upload pictures to the workshop it would turn into nsfw hell_
> > 
> > 
> > What does nsfw mean?
> 
> May I remind you of [this part in the GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#:~:text=You%20must%20be%20age%2013%20or%20older.%20While%20we%20are%20thrilled%20to%20see%20brilliant%20young%20coders%20get%20excited%20by%20learning%20to%20program%2C%20we%20must%20comply%20with%20United%20States%20law.%20GitHub%20does%20not%20target%20our%20Service%20to%20children%20under%2013%2C%20and%20we%20do%20not%20permit%20any%20Users%20under%2013%20on%20our%20Service.)?

Ok so it's something inappropriate I see

**Comment by PossiblyRemember** [comment] 2022-11-19 18:37
> > > > Duplicate of #1972
> > > > _also, if people could upload pictures to the workshop it would turn into nsfw hell_
> > > 
> > > 
> > > What does nsfw mean?
> > 
> > 
> > May I remind you of [this part in the GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#:~:text=You%20must%20be%20age%2013%20or%20older.%20While%20we%20are%20thrilled%20to%20see%20brilliant%20young%20coders%20get%20excited%20by%20learning%20to%20program%2C%20we%20must%20comply%20with%20United%20States%20law.%20GitHub%20does%20not%20target%20our%20Service%20to%20children%20under%2013%2C%20and%20we%20do%20not%20permit%20any%20Users%20under%2013%20on%20our%20Service.)?
> 
> Ok so it's something inappropriate I see

I believe his point was that, saying you don't know what NSFW means, you are assumed to be under the age of thirteen. In this case, you should not be allowed to have a GitHub account for it collects user data, and according to law, user data of children is not allowed to be collected. GitHub can also have a poisonous community, depending on where you go, making it not the best place for a child. For more information, view the [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#:~:text=You%20must%20be%20age%2013%20or%20older.%20While%20we%20are%20thrilled%20to%20see%20brilliant%20young%20coders%20get%20excited%20by%20learning%20to%20program%2C%20we%20must%20comply%20with%20United%20States%20law.%20GitHub%20does%20not%20target%20our%20Service%20to%20children%20under%2013%2C%20and%20we%20do%20not%20permit%20any%20Users%20under%2013%20on%20our%20Service.). If it is found that you are under thirteen, your account will be terminated immediately.

**Comment by ATPGaming** [comment] 2022-11-19 21:38
> 

I'm not a child lmao, unless you count 14 as a child

**Closed** 2022-11-20 01:22 UTC
Labels: feature-request
