### ISSUE TITLE
Water Pressure

### ISSUE THREAD

**Issue by ToadInfinite** [studio-minus/ppg-bugs-and-requests#1079] opened 2022-04-09 00:35 UTC
**Feature description**
It is a system for the map of "Sea" or generally for maps that use water. The idea of having pressure is the fact that if any object or human goes too deep in the water, pressure kicks in and as they go deeper, they start to get tighter and tighter, and seen to be crushed

**Feature purpose**
This adds more of a cool feature to how the Sea map should be like, even then if it may not be too deep. This recently came to my head after I played with some workshop items or presets w/ the sea map, and instantly came to my head with the idea of having this feature. The sole purpose is to have the ability for water to crush a human's body or object at whatever depth they are at. The deeper, the tighter it gets for the human to withstand, and it is not implemented yet, so I do hope it gets added!

**Comment by 5hart** [comment] 2022-04-09 03:45
It would also be cool to see people suffer pressure changed when coming back up, like they might pass out or die from the sudden change in pressure as well. Great idea!

**Comment by DindinYT37** [comment] 2022-04-09 07:15
Duplicate of #243

**Comment by TheBeeThat** [comment] 2022-04-09 11:12
> Duplicate of #243

🤓

**Comment by DindinYT37** [comment] 2022-04-09 11:35
> > Duplicate of #243
> 
> 🤓

It was literally rejected before, so why request it again? And in general, already existing requests will (in most cases) be ignored - especially if the original request already had an answer to it like in this case.

**Comment by ppgplayer** [comment] 2022-04-09 12:52
> 🤓

🤓

**Comment by ppgplayer** [comment] 2022-04-09 12:52
> > > Duplicate of #243
> > 
> > 
> > 🤓
> 
> It was literally rejected before, so why request it again? And in general, already existing requests will (in most cases) be ignored - especially if the original request already had an answer to it like in this case.

🤓

**Comment by Skiiitles** [comment] 2022-04-10 06:27
> Duplicate of #243

What a classic blunder, who doesnt have all 900+ suggestions memorized. If you don't spend all your free time memorizing suggestions and minimoding what are you even doing with your life smh

**Comment by DindinYT37** [comment] 2022-04-10 08:05
> > Duplicate of #243
> 
> What a classic blunder, who doesnt have all 900+ suggestions memorized. If you don't spend all your free time memorizing suggestions and minimoding what are you even doing with your life smh

It's called spending 5 seconds of your life on the search feature, and it's not mini modding, it's just common sense.

**Closed** 2022-04-10 12:21 UTC
Labels: feature-request
