### ISSUE TITLE
Tracers have inconsistent penetration 

### ISSUE THREAD

**Issue by weirdo001** [studio-minus/ppg-bugs-and-requests#1827] opened 2022-07-21 09:07 UTC
**Describe the bug**
See the title. Tracers can penetrate more around specific distances than usual. Raycast bullets do not have this issue. For some reason, this either does not occur or is much less extreme in slow motion.

**Clearly describe how to reproduce the bug**
Get a bulletproof sheet and a submachine gun. Freeze the sheet in the air and start shooting the sheet. Move the smg around different distances, and at some distance, around 3.3m for the submachine gun, it will be able to penetrate as if it was at point blank distance. This "sweet spot" appears to be different for other weapons. I am unsure if there are multiple sweet spots.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9157902/exported.game.debug.info.md)

**Comment by DindinYT37** [comment] 2022-07-21 10:02
Duplicate of #551

**Closed** 2022-07-23 15:26 UTC
Labels: bug
