### ISSUE TITLE
Water physics

### ISSUE THREAD

**Issue by ppgenjoyer** [studio-minus/ppg-bugs-and-requests#2393] opened 2022-11-12 22:20 UTC
**Feature description**
like if you dropped a human into the water would move around it just like real life
**Feature purpose**
It would make the game more fun and also would be cool to see

**Additional context**
Oh and if you wanted there could be waves and tsunamis that you could create.

**Comment by royalealbert27** [comment] 2022-11-13 09:41
already been suggested + developer said it won't be added

**Comment by Drogo-man** [comment] 2022-11-13 10:26
This is one of those things that everyone wants but won't ever be added because it's such a hassle to add and it's basically useless.

**Comment by DindinYT37** [comment] 2022-11-13 12:33
Related to or Duplicate of:
* #359
* #418
* #597
* #756 
* #792 
* #849 
* #941 
* #997 
* #1068 
* #1154 
* #1234 
* #1325 
* #1520 
* #1610 
* #1791 
* #2230

Also, I'm pretty sure he was talking about the water in the sea map being able to have waves, not having actual water physics.

**Comment by bibbybabby** [comment] 2022-11-14 05:11
> Also, I'm pretty sure he was talking about the water in the sea map being able to have waves, not having actual water physics.

>like if you dropped a human into the water would move around it just like real life

**Comment by DindinYT37** [comment] 2022-11-14 07:31
> > Also, I'm pretty sure he was talking about the water in the sea map being able to have waves, not having actual water physics.
> 
> > like if you dropped a human into the water would move around it just like real life

Yep, being able to have waves. He's just really crap at explaining.

**Closed** 2022-12-31 01:56 UTC
Labels: feature-request
