### ISSUE TITLE
Attachments on guns don't work with humans

### ISSUE THREAD

**Issue by mishamumia** [studio-minus/ppg-bugs-and-requests#2582] opened 2022-12-25 22:23 UTC
### Describe the bug

When a player attaches an attachment to a gun and gives it to a human, the attachment still collides with the human.

### Clearly describe how to reproduce the bug

1. Attach any attachment to any gun.
2. Give a gun with an attachment to human.
3. Try to make the human rotate his arm 360°.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10300691/exported.game.debug.info.md)

**Comment by bibbybabby** [comment] 2022-12-26 07:05
Duplicate of #2545

**Closed** 2022-12-27 16:02 UTC
Labels: bug
