### ISSUE TITLE
Bullets go anywhere on left facing guns

### ISSUE THREAD

**Issue by Alexthebug** [studio-minus/ppg-bugs-and-requests#388] opened 2021-10-31 18:42 UTC
**Describe the bug**
Bullets will just fly anywhere with guns spawned to the left

**Clearly describe how to reproduce the bug**
Spawn a gun facing to the left and shoot it

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version:1.22 beta 4
 - GPU:NVIDIA GeForce GTX 960M
 - CPU:Intel I7

**Additional notes**

**Comment by mestiez** [comment] 2021-10-31 19:18
Duplicate of #385

**Closed by mestiez** 2021-10-31 19:18 UTC
Labels: bug
