### ISSUE TITLE
blood texture inside android [1.26 preview 4]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2149] opened 2022-09-17 01:29 UTC
**Describe the bug**
so i made a android fight a human and there's no blood on android then made its skin disingerate then the blood is there!
image: 
![image](https://user-images.githubusercontent.com/101178735/190835241-3b11dc48-bdbc-41c5-bb3d-3b17a14a1970.png)

**Clearly describe how to reproduce the bug**
1. get android
2. get human then smash the human into the android
3. remove android skin

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9590704/exported.game.debug.info.md)

**Comment by ATPGaming** [comment] 2022-09-17 03:03
he absorbed the blood as fuel

**Comment by DindinYT37** [comment] 2022-09-17 09:58
Duplicate of #1474

**Comment by bibbybabby** [comment] 2022-09-17 15:43
> Duplicate of #1474

no thats for decals staying, this one is for decals below skin bug

**Comment by mestiez** [comment] 2022-09-18 14:27
fixed!! Thanks for reporting

**Closed by mestiez** 2022-09-18 14:27 UTC
Labels: bug
