### ISSUE TITLE
Reverse Thrust

### ISSUE THREAD

**Issue by xProBomb** [studio-minus/ppg-bugs-and-requests#2041] opened 2022-09-01 06:04 UTC
**Describe the bug**
A lot of thrusters cause the thrusters to move backwards

**Clearly describe how to reproduce the bug**
Line up 50 (confirmed working for me with 50) Thrusters and connect them all to the "Main" Thruster to avoid jittering, power them all fully, and then let them go, they move backwards. 
using 4 Strong Springs (one at each corner) makes it easy to see the shift from forward to backwards as thrust reaches a critical point. or a industrial gyrostabilizer.

**Mod list**
No Mods

**System info (please complete the following information)**
 - Operating system: Windows 10  (10.0.19044) 64bit
 - Game version: 1.26 preview 2
 - GPU: NVIDIA GeForce RTX 3070 Ti
 - CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- Memory: 64 GB

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9467246/exported.game.debug.info.md)

**Additional notes**

**Comment by xProBomb** [comment] 2022-09-01 06:07
https://steamcommunity.com/sharedfiles/filedetails/?id=2857077923
Here is a upload of the contraption used.

**Comment by DindinYT37** [comment] 2022-09-01 06:29
Duplicate of #2040

**Comment by DindinYT37** [comment] 2022-09-01 06:29
You can also edit issues instead of making a new one.

**Comment by mestiez** [comment] 2022-09-01 13:25
This could be because the exhaust and intake forces are overcoming the actual thrust at some point?

**Closed** 2023-10-11 15:28 UTC
Labels: bug
