### ISSUE TITLE
Able to reattach detached body parts

### ISSUE THREAD

**Issue by gogo1701** [studio-minus/ppg-bugs-and-requests#1652] opened 2022-07-08 18:16 UTC
**Feature description**
To be able to reattach a detached body part, by having a machine, or just connecting it with wires to connect it and make it functional again.

**Feature purpose**
The purpose is so we can make surgery RP or at all the game more realistic.

**Comment by SirAJ4895** [comment] 2022-07-08 19:16
Full support

**Comment by PossiblyRemember** [comment] 2022-07-08 21:57
I would love this to be a feature, but truth be told it would probably be a real pain to implement this. However, I did find a [mod](https://steamcommunity.com/sharedfiles/filedetails?id=2801931724), although unstable

**Comment by DindinYT37** [comment] 2022-07-08 21:57
Basically a duplicate of #1631.

**Closed** 2022-07-09 14:16 UTC
Labels: feature-request
