### ISSUE TITLE
Add recompile button always there

### ISSUE THREAD

**Issue by WhiteholeSteve** [studio-minus/ppg-bugs-and-requests#1072] opened 2022-04-08 09:58 UTC
**Feature purpose*
Make it always there, so us modders don't have to reload ppg

**Comment by DindinYT37** [comment] 2022-04-08 10:06
Please use the template, and this was already requested several times and rejected before.

**Comment by DindinYT37** [comment] 2022-04-08 10:06
Duplicate of #694 and #589 - similar to #605.

**Comment by WhiteholeSteve** [comment] 2022-04-08 10:07
oh okay

**Closed** 2022-04-08 20:01 UTC
Labels: feature-request
