### ISSUE TITLE
make it easier for humans to hold thing

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1822] opened 2022-07-20 19:53 UTC
**Feature description**
when a human is holding an object, the object should automatically rotate to correctly fit the human's hand. this only happens on pickup so you can pause and change it

**Feature purpose**
Makes it less of a pain for humans to hold items. i think people would like this change

**Comment by DindinYT37** [comment] 2022-07-20 19:56
That would be counter-productive because people would have to readjust the objects they have already adjusted beforehand.

**Comment by DindinYT37** [comment] 2022-07-20 19:58
Duplicate of or Related to:
* #763
* #821
* #1627

**Comment by ATPGaming** [comment] 2022-07-20 20:02
> That would be counter-productive because people would have to readjust the objects they have already adjusted beforehand.

ok it can be turned off

**Comment by ATPGaming** [comment] 2022-07-20 20:02
> Duplicate of or Related to:
> 
> * [Humans hold guns weird, unless you place it perfectly, maybe make prebuilt ones? #763](https://github.com/studio-minus/ppg-bugs-and-requests/issues/763)
> * ["hold pose" option in the context menu #821](https://github.com/studio-minus/ppg-bugs-and-requests/issues/821)
> * [New Default Weapon Holding Style *Revolver* #1627](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1627)
> * [Match Object Rotation #1820](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1820)

those literally aren't related

**Closed** 2022-07-20 20:03 UTC
Labels: feature-request

**Comment by DindinYT37** [comment] 2022-07-20 20:07
> > That would be counter-productive because people would have to readjust the objects they have already adjusted beforehand.
> 
> ok it can be turned off

So basically you're telling me you want a personal feature, not one for the community.

**Comment by DindinYT37** [comment] 2022-07-20 20:07
> > Duplicate of or Related to:
> > 
> > * [Humans hold guns weird, unless you place it perfectly, maybe make prebuilt ones? #763](https://github.com/studio-minus/ppg-bugs-and-requests/issues/763)
> > * ["hold pose" option in the context menu #821](https://github.com/studio-minus/ppg-bugs-and-requests/issues/821)
> > * [New Default Weapon Holding Style _Revolver_ #1627](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1627)
> > * [Match Object Rotation #1820](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1820)
> 
> those literally aren't related

They indeed are.

**Comment by DindinYT37** [comment] 2022-07-20 20:31
> > So basically you're telling me you want a personal feature, not one for the community.
> 
> I'm really sorry for making a bad suggestion but it's closed so stop criticizing me please

Apologizing won't make me stop, you have to correct yourself to make me stop criticizing. That's how it works.

**Comment by ATPGaming** [comment] 2022-07-20 20:33
Sir, I already closed it... I DID correct myself by closing it. I feel like this is getting towards harassment, I'm not going to reply anymore and again I'm sorry for bad suggesting, and sorry if I ruined your day

**Comment by DindinYT37** [comment] 2022-07-20 20:35
> Sir, I already closed it... I DID correct myself by closing it. I feel like this is getting towards harassment, I'm not going to reply anymore and again I'm sorry for bad suggesting, and sorry if I ruined your day

I know you already corrected yourself **here**, but you asked me to stop criticizing you in **general**. So you have to correct yourself in **general**, not in this single issue. This isn't going towards harassment, you're just insanely bad at taking any criticism at all. You didn't ruin my day, you ruined your own day by making such a big deal out of this when I'm just telling you the same thing over and over again because you keep repeating it.
