### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Karmy8** [studio-minus/ppg-bugs-and-requests#2395] opened 2022-11-13 20:42 UTC
Multiplayer:
Add a button that lets you create a server and connect with a friend.
Since there's no character you will be able to see your friends name on steam right next to their cursor.
Some things to add in a multiplayer feature:
- See what they spawn.
- See what they delete.
- See what properties they modify like: object temperature, object angle, etc.
- See how they arrange the wires.
I think that everyone wants a multiplayer feature.

**Comment by ATPGaming** [comment] 2022-11-13 21:10
Please use the template

Duplicate of:
2395
2299
2189
1055
922
784
475
238
194

**Comment by Drogo-man** [comment] 2022-11-14 05:33
Not you too

**Comment by royalealbert27** [comment] 2022-11-14 13:57
developer said it won't ever get added + already been suggested since the dawn of time

**Closed** 2022-11-18 00:18 UTC
Labels: feature-request
