### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by DemonPig666** [studio-minus/ppg-bugs-and-requests#2226] opened 2022-10-01 21:01 UTC
**Feature description** 
Hear me out.
We need doors in PPG. Why don't we have doors yet. They would be so cool you could even have a special door that needs an activation signal to unlock. Oooo and factory doors sliding doors oh the possibilities. Please add doors.

**Feature purpose**
We may have mods and pistons but to have official doors would be cool. This would allow for blocked areas that things cannot pass through but when opened allow things to pass through.

**Additional context**
I know this is a duplicate of #1813 but I didn’t notice before.

**Comment by DindinYT37** [comment] 2022-10-01 21:03
Duplicate of #1813

**Comment by DindinYT37** [comment] 2022-10-01 21:04
Also, please use a template and fill it out.

**Comment by bibbybabby** [comment] 2022-10-01 21:05
Use https://steamcommunity.com/sharedfiles/filedetails/?id=2403302283 for normal doors and pistons for sliding factory doors

**Comment by DemonPig666** [comment] 2022-10-02 13:06
Ok sorry

**Closed** 2022-10-09 12:38 UTC
