### ISSUE TITLE
metal itens bending

### ISSUE THREAD

**Issue by birbhimself** [studio-minus/ppg-bugs-and-requests#1222] opened 2022-05-08 21:28 UTC
**Feature description**
add an option that when you toggle it metal itens bend when really hot

**Feature purpose**
it would be really cool for blacksmithing

**Additional context**
please for gods sake make it an option or it will fuck most contraptions

**Comment by DindinYT37** [comment] 2022-05-08 21:40
Basically duplicate of #659

**Closed** 2022-05-08 22:34 UTC
Labels: feature-request

**Comment by YourLocalPlonker** [comment] 2022-05-09 15:13
how about metal bends not only if it is hot but also when it is normal temp just requires more force?

**Comment by DindinYT37** [comment] 2022-05-09 16:03
> how about metal bends not only if it is hot but also when it is normal temp just requires more force?

It was already rejected...

**Comment by YourLocalPlonker** [comment] 2022-05-09 18:40
> how about metal bends not only if it is hot but also when it is normal temp just requires more force?

what a shame but I understand that it would be a pain in the ass to code this
