### ISSUE TITLE
Optimze Fire

### ISSUE THREAD

**Issue by DankamaTank985** [studio-minus/ppg-bugs-and-requests#1121] opened 2022-04-13 22:19 UTC
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?
Right now fire runs like a turd
**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?
Make fire run good
**Additional context**
I have a rx 6600 and a i5-12400 with 32 gb of ram. I light like 4 things on fire and my frame rate drops from 800~ fps to barely 60 fps

**Comment by DindinYT37** [comment] 2022-04-13 22:27
That's not how a suggestion works... you haven't removed the placeholders, and this isn't even a feature request.

**Comment by mestiez** [comment] 2022-04-14 16:12
Duplicate of #802

**Closed by mestiez** 2022-04-14 16:12 UTC
Labels: feature-request
