### ISSUE TITLE
colourable wires

### ISSUE THREAD

**Issue by cuptaza** [studio-minus/ppg-bugs-and-requests#2420] opened 2022-11-18 01:18 UTC
### Feature description

adds a wire that when selected will first request the color for the main cable then will request another color for when the cable is powered
if selected whit keypad will use last color combination

### Feature purpose

because, anyone could make cool scenes and also you could make when the cable is powered the same color of the main cable to hide if its powered, i dont know if there is a mod of this but please make it

**Comment by mestiez** [comment] 2022-11-19 21:17
More or less a duplicate of #2410

**Closed** 2022-11-19 21:17 UTC
Labels: feature-request
