### ISSUE TITLE
Sentry Turret freaks out when touching anything / falling

### ISSUE THREAD

**Issue by MrN1fto** [studio-minus/ppg-bugs-and-requests#2291] opened 2022-10-22 17:32 UTC
**Describe the bug**
When the Sentry Turret exists, it moves around incredibly fast and breaks the game

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Spawn the turret, sometimes it will act normal, then break a few seconds later.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
No Mods

**System info (please complete the following information)**
 - Operating system: Win 10
 - Game version: 1.24 Patch 5
 - GPU: Nvidia GeForce GTX 1660 TI 
 - CPU: Intel i7-10700F CPU @ 2.90GHz

**Additional notes**
N/A

**Comment by DindinYT37** [comment] 2022-10-22 18:42
Duplicate of #1568

**Closed** 2023-08-20 12:50 UTC
Labels: bug
