### ISSUE TITLE
mod search bar

### ISSUE THREAD

**Issue by cookie622W** [studio-minus/ppg-bugs-and-requests#517] opened 2021-11-17 18:30 UTC
when I looking for a mod it would nice to have a search bar because I have like 50 mods

**Comment by UniDuki** [comment] 2021-11-17 20:34
You were told to follow the template in #250, yet you still are not following the template. It is not that hard.

**Comment by mestiez** [comment] 2021-11-18 11:50
Duplicate of #250 and you are also permanently banned

**Closed by mestiez** 2021-11-18 11:50 UTC
Labels: feature-request
