### ISSUE TITLE
Crouch Animation

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#454] opened 2021-11-07 00:30 UTC
A simple right click menu option to put the human into a crouch stance.

The purpose of this feature is simply to make cooler poses, better battle scenes, and that along some other things.

![image](https://user-images.githubusercontent.com/89762931/140627873-7f64ff56-1411-4726-ab21-8a85c9315e9a.png)
 like the image above.

**Comment by TamasB14** [comment] 2021-11-07 18:00
https://github.com/studio-minus/ppg-bugs-and-requests/issues/255 I did ask for that feature too.

**Comment by mestiez** [comment] 2021-11-08 21:36
Duplicate of #255

**Closed by mestiez** 2021-11-08 21:36 UTC
Labels: feature-request
