### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by Tyosef** [studio-minus/ppg-bugs-and-requests#1227] opened 2022-05-11 19:30 UTC
The layers menu is what i am planning to suggest, maybe a menu enabled in an advanced tab or something, but it basically controls what the stacking order for things is when you save or are building.

It is useful because it will allow large creators to make things that look ugly due to stacking issues less ugly, and it’ll allow players to get into advanced building and make beginners find it easier to make more complex things.

I’d personally expect it to be a tab for the sidepanels which has a custom number in it which has to be an integer, maybe it could have arrows on either side for increase and decrease?

**Comment by DindinYT37** [comment] 2022-05-11 19:47
Would be nice if you kept the headers of the template.

**Comment by mestiez** [comment] 2022-05-12 13:16
duplicate of #838

**Closed by mestiez** 2022-05-12 13:16 UTC
Labels: feature-request
