### ISSUE TITLE
Magnet that attracts everything

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2394] opened 2022-11-13 00:45 UTC
**Feature description**
Add some sort of magnet that attracts any item

**Feature purpose**
It would be fun to just suck everything into one place like a black hole

**Comment by royalealbert27** [comment] 2022-11-13 09:40
pull power

**Comment by Drogo-man** [comment] 2022-11-13 10:27
I think he means it attrects not Magnetic things.

**Comment by DindinYT37** [comment] 2022-11-13 12:34
Duplicate of or Related to:
* #156
* #700
* #2006

**Closed** 2022-11-13 16:02 UTC
Labels: feature-request
