### ISSUE TITLE
Prosthetic limbs

### ISSUE THREAD

**Issue by Deadhourd** [studio-minus/ppg-bugs-and-requests#1212] opened 2022-05-04 16:04 UTC
new item that is spawnable

To give humans or androids new limbs in the case one rots and you remove it you can give it a new limb

**Comment by DindinYT37** [comment] 2022-05-04 16:28
Please use the template. Also, I'm pretty sure something similar to this was already mentioned in another issue.

**Comment by mestiez** [comment] 2022-05-12 13:21
duplicate of #254

**Closed by mestiez** 2022-05-12 13:21 UTC
Labels: feature-request
