### ISSUE TITLE
Water (flask)

### ISSUE THREAD

**Issue by MartinRDR** [studio-minus/ppg-bugs-and-requests#1002] opened 2022-03-27 12:47 UTC
**Feature description**
Spawnable item, just like any flask of liquids, but it contains water.

**Feature purpose**
No major purpose, but with the liquid outlet, it would be able to clean off dirt (from explosions) and blood instead of using the soap bar.

**Additional context**
It should not leave any stains, but if it would, it would just stay as a stain for maybe 15 to 30 seconds then slowly fade away?
![Screenshot_13](https://user-images.githubusercontent.com/102469388/160281789-5d7688af-c121-404b-8785-f227d0392006.png)
This is what I have in mind of the texture.

**Comment by DindinYT37** [comment] 2022-03-27 13:31
Duplicate of #904

**Closed** 2022-05-15 21:49 UTC
Labels: feature-request
