### ISSUE TITLE
new gas system / ignitable gas

### ISSUE THREAD

**Issue by basedkit** [studio-minus/ppg-bugs-and-requests#1118] opened 2022-04-13 07:54 UTC
**Feature description**
a new gas system that would act the same as the flame thrower and a fire extinguisher, it could either be a new setting added to the liquid container or its own new item that needs to be connected to a liquid container.

**Feature purpose**
I've always wanted to make my own jet engine in this game and with the new nitroglycerin power buff I've been able to make some cool fluid powered stuff that acts like a jet, but it still doesn't really feel like a proper jet engine. so by adding a gas system it would not only let me create a proper jet it would also open up some seriously cool creation ideas for much of the building side of the community.

**Additional context**
I 100% understand that the coding side of this could be difficult so I would love your input on the feasibility of this concept :)

**Comment by mestiez** [comment] 2022-04-13 09:42
Duplicate of  #423

**Comment by mestiez** [comment] 2022-04-13 09:43
motherfuck misclick

**Closed** 2022-04-13 09:42 UTC
Labels: feature-request

**Comment by basedkit** [comment] 2022-04-14 04:16
oh i guess this isnt a new idea lmfao
