### ISSUE TITLE
Armor or clothes

### ISSUE THREAD

**Issue by BobbyG555** [studio-minus/ppg-bugs-and-requests#2140] opened 2022-09-15 16:29 UTC
**Feature description**
Clothes or armour of some sort. Armor to make the ragdolls more resistant, and some armour with spikes of some sort to spike whoever wears it.

**Feature purpose**
To make characters be more resistant or dead.

**Additional context**
Maybe add different types, like iron helmets or leather chestplate. I made a image of the spike helmets(its bad i know¯\_(ツ)_/¯)
![Uploading PPG Spike helmet.png…]()

**Comment by DindinYT37** [comment] 2022-09-15 17:26
Duplicate of or Related to:
* #1175
* #1849
* #1999

**Closed** 2022-09-15 23:01 UTC
Labels: feature-request
