### ISSUE TITLE
Diffrent bleeding(ish) from decapitation

### ISSUE THREAD

**Issue by Squibard** [studio-minus/ppg-bugs-and-requests#2606] opened 2022-12-30 02:04 UTC
### Feature description

I would like for after humans are decapitated their blood would squirt out in pulses like their heartbeat then just fade out to just bleeding

### Feature purpose

to enhance realisim

### Additional context

idk if this is possible

**Comment by mestiez** [comment] 2022-12-30 20:05
Duplicate of #1703, probably

**Closed** 2022-12-30 20:05 UTC
Labels: duplicate, feature-request
