### ISSUE TITLE
multiplayer

### ISSUE THREAD

**Issue by picercian** [studio-minus/ppg-bugs-and-requests#2189] opened 2022-09-25 01:52 UTC
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?
multiplayer. in the main menu, there will be a multiplayer button. Clicking it will send you to a different screen with 2 buttons. join someone and make a multiplayer game. after making a multiplayer game, you have the choice between private or public, both giving you a code. you can put in the code in the join someone tab. There will also be an area to join public games. Finally, you can set how many people can join, the password, and the game.
**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?
I wanted to play with friends but couldn't.
**Additional context**

**Comment by Drogo-man** [comment] 2022-09-25 03:05
Oh no.

**Comment by ATPGaming** [comment] 2022-09-25 07:07
How do you expect zooi to do this? Multiplayer is extremely hard to create

**Comment by DindinYT37** [comment] 2022-09-25 10:40
Duplicate of:
* #194
* #475
* #784
* #922
* #1055

This was rejected a lot already and it was also stated on the People Playground Roadmap that Multiplayer will not be added.

**Comment by Drogo-man** [comment] 2022-09-25 15:15
This is one of the things on the list of "things that wont be added, but a bunch of random 9 years olds will beg for it anyway".

**Closed** 2022-09-26 15:23 UTC
Labels: feature-request
