### ISSUE TITLE
physics gun disabling itself for a second 

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1742] opened 2022-07-14 21:19 UTC
**Describe the bug**
when a physics gun is hooked up to a activation toggle and it will stop working for a second every time you unpause the game

**Clearly describe how to reproduce the bug**
spawn activation toggle
spawn physics gun
hook them up with propagation wires 
freeze both of them 
make it grab some object then pause the game and unpause, the object will go down slowly with every unpause

**Mod list**
None
**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.25
 - GPU: gtx 1650 super
 - CPU: intel i5

**Additional notes**

**Comment by mestiez** [comment] 2022-07-15 10:17
Duplicate of something i dont remember but i know its there

**Closed by mestiez** 2022-07-15 10:17 UTC
Labels: bug

**Comment by DindinYT37** [comment] 2022-07-15 10:20
> Duplicate of something i dont remember but i know its there

* #663
