### ISSUE TITLE
water releasing power

### ISSUE THREAD

**Issue by leastoundeos** [studio-minus/ppg-bugs-and-requests#1791] opened 2022-07-17 18:54 UTC
**Feature description**
it's a new power that can release water when we press the mouse and it's meant to be located in powers tab

**Feature purpose**
the main purpose of this power is that if we keep holding the mouse button the water can raise in the level and can even drown a human if he is not on top of a object that will not let him fall to the water, otherwise he would drown, i wanted so much this power cause it's being a long time that we don't have a new power in ppg.

**Additional context**
this power acts as a hose that releases water and if we let splashing water for a few seconds the water can raise in the level and also serves to extinguish fire on a body.

**Comment by DindinYT37** [comment] 2022-07-17 19:02
Related to or Duplicate of:
* #359
* #413 
* #418
* #597
* #610
* #756 
* #790
* #792 
* #844 
* #849 
* #854 
* #904 
* #917 
* #941 
* #997 
* #1002 
* #1068 
* #1076 
* #1154 
* #1182 
* #1188 
* #1189 
* #1190 
* #1234 
* #1244 
* #1261 
* #1262 
* #1287 
* #1325 
* #1380 
* #1520 
* #1610

**Comment by SirAJ4895** [comment] 2022-07-17 22:04
> Related to or Duplicate of:
> 
> * [Showerhead water interaction #359](https://github.com/studio-minus/ppg-bugs-and-requests/issues/359)
> * [Water liquid. #413](https://github.com/studio-minus/ppg-bugs-and-requests/issues/413)
> * [Waves #418](https://github.com/studio-minus/ppg-bugs-and-requests/issues/418)
> * [Spawnable water? #597](https://github.com/studio-minus/ppg-bugs-and-requests/issues/597)
> * [Balloons can store liquids + maybe helium? #610](https://github.com/studio-minus/ppg-bugs-and-requests/issues/610)
> * [Water Level/Change Water to Something else #756](https://github.com/studio-minus/ppg-bugs-and-requests/issues/756)
> * [water cannon/long range fire extinguisher #790](https://github.com/studio-minus/ppg-bugs-and-requests/issues/790)
> * [Water #792](https://github.com/studio-minus/ppg-bugs-and-requests/issues/792)
> * [bottles can be filled and dispersed into a pool of water #844](https://github.com/studio-minus/ppg-bugs-and-requests/issues/844)
> * [Water is not pouring #849](https://github.com/studio-minus/ppg-bugs-and-requests/issues/849)
> * [Water does not fill items.  #854](https://github.com/studio-minus/ppg-bugs-and-requests/issues/854)
> * [Water in flask #904](https://github.com/studio-minus/ppg-bugs-and-requests/issues/904)
> * [Water as a usable fluid #917](https://github.com/studio-minus/ppg-bugs-and-requests/issues/917)
> * [Puddles #941](https://github.com/studio-minus/ppg-bugs-and-requests/issues/941)
> * [Are there any new powers/environment settings in thought? #997](https://github.com/studio-minus/ppg-bugs-and-requests/issues/997)
> * [Water (flask) #1002](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1002)
> * [Human Oxygen shouldn't be consumed if their front face isn't submerged in water #1068](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1068)
> * [Elemental #1076](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1076)
> * [Extreme Realistic Water?!?!? #1154](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1154)
> * [I want a water pump that can work with electricity, that is, with any power source, this pump will work and draw water when it is powered, but a new tool hose will be needed to carry the water. We will be able to extinguish the fires with splitting water and wipe the blood and explosion stains on the ground, and especially the fires need to be extinguished with water, besides, we will combine soap and water and make foam and use them to extinguish oil fires, I hope it will be added to the 1.24 update. #1182](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1182)
> * [my request is that if a generator is connected and started while a water pump is in contact with any water, pressing the f key will pump water into the hose, which is the new tool, but it will be necessary to connect the hose to a valve, thanks to this, we will be able to really extinguish the fires with water. #1188](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1188)
> * [Please add the water pump, the new tool, I want to put it together with the hose and put it in a fire truck and extinguish the fire with the hose so much !!! #1189](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1189)
> * [In order to extinguish the fire with water in the game, it is only necessary to contact the fire with water, but thanks to my great idea, this will not be necessary. You will add the fire extinguisher used by real life firefighters to the game as in my idea, and also the pressure of the pump in my idea can be adjusted, I hope it will be added in the 1.24 update. #1190](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1190)
> * [Spawnable liquids + Weather #1234](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1234)
> * [Water as a liquid #1244](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1244)
> * [Water pump #1261](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1261)
> * [Water liquid  #1262](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1262)
> * [People on fire to be extinguished in water. #1287](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1287)
> * [Realistic Water #1325](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1325)
> * [Water (not useless) #1380](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1380)
> * [Waterblock #1520](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1520)
> * [Wind/air push power #1610](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1610)

JESUS CHRIST!!!

**Closed** 2022-07-23 15:53 UTC
Labels: feature-request
