### ISSUE TITLE
Option to not center-scale things

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#1088] opened 2022-04-10 04:46 UTC
**Feature description**
Basically be able to toggle whether or not objects scale from the center, like instead of scaling with the center fixed, it will stretch from only the side you are stretching it from, and none of the other sides move.

**Feature purpose**
I find it somewhat of a hassle to deal with this when I'm scaling things, as it won't be as accurate since I have to move it around to see how much it's scaling.

**Comment by ppgplayer** [comment] 2022-04-10 06:59
yes

**Comment by DindinYT37** [comment] 2022-04-10 08:02
Duplicate of #540

**Comment by 5hart** [comment] 2022-04-10 08:04
> Duplicate of #540

Oh, sorry, I didn’t see that you already made an issue regarding it. I noticed zooi noticed it and was asking about it. Do you think it’ll be added? I hope so, I could really use it 😅

**Comment by DindinYT37** [comment] 2022-04-10 09:03
> > Duplicate of #540
> 
> Oh, sorry, I didn’t see that you already made an issue regarding it. I noticed zooi noticed it and was asking about it. Do you think it’ll be added? I hope so, I could really use it 😅

Same, it's a nice thing to have but I think my issue was kinda forgotten anyway so this one is a nice bump I guess.

**Closed** 2022-04-10 11:45 UTC
Labels: feature-request
