### ISSUE TITLE
Flamethrower rework.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#377] opened 2021-10-31 10:09 UTC
Flamethrower should work like powered liquid outlet, but it will spread burning napalm instead regular liquid.

At this moment flamethrower is not not, have very small range(3 meters) and burn trough walls.

**Comment by Afavertov** [comment] 2021-10-31 10:18
![изображение](https://user-images.githubusercontent.com/89081329/139577973-d3613ca7-9174-45d4-b6f3-b0c8e50738df.png)

**Comment by mestiez** [comment] 2021-10-31 11:29
Possible duplicate of #299

**Closed** 2021-10-31 11:29 UTC
Labels: feature-request
