### ISSUE TITLE
Cutting/slashing

### ISSUE THREAD

**Issue by AusarDvile** [studio-minus/ppg-bugs-and-requests#2774] opened 2023-02-24 18:36 UTC
### Feature description

Cutting and slashing would be amazing as it would add another layer to the game.
The fact that many swords and other weapons only do piercing damage is kind of boring.
I have about 500+ hours on the game and stabbing people which sounds weird is boring but slashing would add another layer not just to weapons but to machines and other things. 
Would be nice if i could make a small scratch on to a test subject or even cut their head or limb off.

### Feature purpose

it does not exist in almost any form.

**Comment by DindinYT37** [comment] 2023-02-27 10:45
Duplicate of or Related to:
* #168
* #672
* #808
* #1432
* #1792
* #2353

**Closed as not planned** 2023-02-28 21:17 UTC
Labels: feature-request
