### ISSUE TITLE
Cannot select, drag, or interact with anything

### ISSUE THREAD

**Issue by SuitedDevil** [studio-minus/ppg-bugs-and-requests#835] opened 2022-03-15 23:07 UTC
Bug:
This is as of the new Preview 1.23 for People Playground. I think the title explains itself, I can't interact with anything, I can spawn things and the saves work fine, kinda, but I can't right click on them, drag over them, or do anything. It also doesn't work in empty space, the drag box doesn't even appear, so it seems more like some sort of input issue? I don't know.

Update: It's not just clicking, it's all input to the play-space, the context menu works just fine, but in the play-space, key-downs, mouse-button inputs, pretty much any interaction is denied, nothing even gets highlighted.

Mod list:
A lot that it would be too many to list, however I don't think this has to do with that, it's mainly just added items, sounds, and guns.

System Info:
OS: Windows 10
Game Version: Preview 1.23
GPU: RTX 2060
CPU: Ryzen 2500 Six-Core

**Comment by hypermodified** [comment] 2022-03-15 23:41
this is also happening to me

**Comment by f4563** [comment] 2022-03-16 00:03
disable ocm

**Comment by SuitedDevil** [comment] 2022-03-16 00:42
> disable ocm

what is ocm?

**Comment by SuitedDevil** [comment] 2022-03-16 00:56
Okay, I unsubscribed from a couple of mods, assuming that OCM is "Overcomplicated Mod" I don't have that, but I had a framework mod for giving people powers, so maybe that was it. I'm unsure, I'm going to keep the thread open though for anyone else who has this problem.

**Comment by DindinYT37** [comment] 2022-03-16 07:07
Duplicate of #829 but can't blame you since it has no real title. Anyways, same.

**Comment by mestiez** [comment] 2022-03-16 07:50
Just to be clear: this is not the mod's fault

**Closed by mestiez** 2022-03-16 07:50 UTC
Labels: bug

**Comment by Aspa102** [comment] 2022-03-20 08:22
> Just to be clear: this is not the mod's fault

I am so confused on what you managed to do to make the mod bug out

**Comment by SuitedDevil** [comment] 2022-11-25 06:09
a
