### ISSUE TITLE
Save Poses

### ISSUE THREAD

**Issue by Toasty122** [studio-minus/ppg-bugs-and-requests#1064] opened 2022-04-05 00:27 UTC
**Feature description**
Be able to save poses

**Feature purpose**
Be able to save poses like in the OCM mod. The OCM mod save poses feature doesn't work that well, so that's why I'm posting this

**Comment by DindinYT37** [comment] 2022-04-05 09:05
Basically a duplicate of #1026

**Comment by Toasty122** [comment] 2022-04-05 22:40
and?

**Comment by DindinYT37** [comment] 2022-04-05 22:46
> and?
> 

A duplicate is invalid.

**Comment by Toasty122** [comment] 2022-04-05 23:31
> > and?
> 
> A duplicate is invalid.

Its not invalid if its not a duplicate

**Comment by DindinYT37** [comment] 2022-04-06 07:57
> > > and?
> > 
> > A duplicate is invalid.
> 
> Its not invalid if its not a duplicate

It is one though, what's your point?

**Comment by UniDuki** [comment] 2022-04-06 11:42
This is not a duplicate of 1026. Yes it is kinda similar, but that does not matter, these are different requests.
This is asking for the ability to save poses, 1026 is asking for more poses and animations.

**Comment by ppgplayer** [comment] 2022-04-07 06:27
> > This is not a duplicate of 1026. Yes it is kinda similar, but that does not matter, these are different requests. This is asking for the ability to save poses, 1026 is asking for more poses and animations.
> 
> It pretty much is, and I quote:
> 
> > I would love to have more animations and/or **poses** [...] it would also be awesome **if i could make my own ones!**
> 
> Edit: @UniDuki you can't dislike my comment for no reason...

He can, who said he couldn't?

**Comment by ahlad69** [comment] 2022-04-10 03:55
> Basically a duplicate of #1026

holy shit who cares, you have no affiliation with studio minus and no affiliation with bitches

**Comment by DindinYT37** [comment] 2022-04-10 08:12
> > Basically a duplicate of #1026
> 
> holy shit who cares, you have no affiliation with studio minus and no affiliation with bitches

It's common sense among GitHub.

**Comment by mestiez** [comment] 2022-04-10 12:05
Duplicate of #1026

**Closed by mestiez** 2022-04-10 12:05 UTC
Labels: feature-request
