### ISSUE TITLE
Water as a liquid

### ISSUE THREAD

**Issue by TheLivingM3m3** [studio-minus/ppg-bugs-and-requests#1244] opened 2022-05-15 20:49 UTC
**Feature description**
Ability to spawn water containers and collect water by submerging a liquid valve and enabling it.

**Feature purpose**
Could be used in conjunction with other liquids to _water_ down the effect they have. Could be used with new liquid canister in the beta to create a ballast tank and pump.

**Comment by DindinYT37** [comment] 2022-05-15 20:59
Duplicate of #917, #1002, and many more.

**Closed** 2022-05-15 21:49 UTC
Labels: feature-request
