### ISSUE TITLE
Enable/disable body decay

### ISSUE THREAD

**Issue by JasonYau9** [studio-minus/ppg-bugs-and-requests#2604] opened 2022-12-29 22:54 UTC
### Feature description

Alr so in gore settings you can toggle on and off if the creatures you kill begin to decay or not

### Feature purpose

The purpose is for players to decide if they want the creatures they kill to decay because it is so gah dayum annoying

**Comment by ATPGaming** [comment] 2022-12-29 23:00
Duplicate of: #1282

**Closed** 2022-12-30 20:01 UTC
Labels: feature-request
