### ISSUE TITLE
Syringe just sticks to someone

### ISSUE THREAD

**Issue by WhiteholeSteve** [studio-minus/ppg-bugs-and-requests#1870] opened 2022-07-25 12:54 UTC
**Describe the bug**
You can't get a syringe out of someone, which is kinda annoying, as I want to get a medical license in game, so please fix

**Clearly describe how to reproduce the bug**
stab someone (any human) with a syringe.

**Mod list**
Supernovasmp mod (the mod I made, I new update I haven't posted)

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.25.4
 - GPU: nvidia geforce GTX 1060 3gb
 - CPU: intel(r) core(tm) i3-4130 cpu @ 3.40 ghz

**Additional notes**

**Comment by DindinYT37** [comment] 2022-07-25 13:04
Doesn't happen for me.

**Comment by mestiez** [comment] 2022-07-25 14:05
I can't reproduce this

**Comment by OoferBOOFER** [comment] 2022-07-25 17:43
what collision quality are you using? that might be effecting it

**Comment by WhiteholeSteve** [comment] 2022-07-27 05:37
Hmm I'll check continous, well idk I'll check if it happens again

**Comment by mestiez** [comment] 2022-08-02 12:19
closing until a reliable way to reproduce is posted

**Closed by mestiez** 2022-08-02 12:19 UTC
Labels: bug, unclear
