### ISSUE TITLE
Bleeding out wayyyyy too heavily

### ISSUE THREAD

**Issue by Notradaem** [studio-minus/ppg-bugs-and-requests#1299] opened 2022-05-18 05:31 UTC
**Describe the bug**
- Humans bleed out in a matter of seconds when you shoot them anywhere but the head, making any bullet unnecessarily lethal.

**Clearly describe how to reproduce the bug**
- Shoot a human so that there's an exit wound, but not in the head. 

**Mod list**
--All of these are inactive--
- Quick Right-Click Options
- Woodland Lake(Map)
- Explosive Mod
- Per Pixel Destruction
- Chemical Warfare
- Active Humans
- Roleplay Weapons
- Weapons Mod
- COMBAT Weapons Pack V3.0
- Doom Weapons Mod
- The Greenbrick Mod

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: Both 1.24 preview 7 (64 bit) and 1.23.10 (64 bit) but the bug happens more often in the beta branch
 - GPU: NVIDIA GeForce GTX 1060 3GB
 - CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz

**I know the guy right before me mentioned this but I'd rather say something than nothing**

**Comment by DindinYT37** [comment] 2022-05-18 07:23
Duplicate of #1298

**Closed** 2022-05-18 09:52 UTC
Labels: bug
