### ISSUE TITLE
Bug report on preview 11 

### ISSUE THREAD

**Issue by yeeteeyt** [studio-minus/ppg-bugs-and-requests#2526] opened 2022-12-08 02:06 UTC
### Describe the bug

1. When a body part is dismembered, it violently explodes.
2. When a body part is dismembered, the heart spawns a few meters away from the corpse.
3. When a body part is dismembered, blood spawns in the corner of the map.
4. When a tire is popped, the rim deforms along with the tire itself.
5. Mods, contraptions from different versions, or just too many items will stop status bars from appearing.
6. Some items disappear when electrocuted. (I'm pretty sure they just fly away really fast, I think electricity knockback should be nerfed)
7. When a large amount of heat or electricity is present, the map glitches out (half of it is black, simultaneously boiling and freezing)
That's all!

### Clearly describe how to reproduce the bug

1. Dismember body part
2. same
3. same
4. Pop car tire
5. Spawn a lot of items or use a mod
6. Electrocute something
7. (most easily done with mods) Spawn a large amount of energy sources and electrocute something with it, aim at making it really hot

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19044) 64bit

 - **CPU**: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

 - **GPU**: NVIDIA GeForce GT 710

 - **Memory**: 16 GB

## All loaded mods

	Aubarino-Node Mapper-2644178588 v1.1 for game v1.20+
		Currently ACTIVE
		Has been initialised

	Brian9171 & chonk-PPG Additions-2844222823 v0.3 for game v1.25+
		Currently ACTIVE

	kortl-COMBAT Props Pack-local v1.0 for game v1.7.x
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently ACTIVE

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently ACTIVE

	Mr_kWKD-Humans+-2168468454 v1.3.0 for game v1.9
		Currently ACTIVE

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently ACTIVE

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently ACTIVE

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently ACTIVE

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently ACTIVE

	Alibarda-PowersMod-2276255188 v2.1 for game v1.18+
		Currently ACTIVE

	Alibarda-Human Tiers-2308911224 v4.8 for game v1.18+
		Currently ACTIVE
		Has been initialised

	Kubulll-Electronic Components-2312233711 v0.4.11 for game v1.17+
		Currently ACTIVE

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently ACTIVE

	jimmyl-Parts and Contraptions-2337159652 v3.9.5 for game v1.18+
		Currently inactive
		Malfunctioning

	PersonMan65-Wierd Syringes Mod-2352420066 v2.2 for game v1.24
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently inactive

	LijmPistool-Liquids Map-2432660281 v1.0 for game v1.14+
		Currently inactive
		Malfunctioning

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently ACTIVE

	Kubulll-Nuclear Playground-2484034390 v1.0 for game v1.21+
		Currently ACTIVE

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently ACTIVE

	Pumpkin-Quality of Life Items-2500516293 v1.7 for game v1.22.3
		Currently inactive
		Malfunctioning

	zooi-Signals and Logic Gates-2504621801 v1.3 for game v1.22.3
		Currently ACTIVE
		Has been initialised

	Voidy-Reattach Limbs-2507657213 v1.0 for game v1.20+
		Currently ACTIVE

	MR.REX-Emergency Siren-2509362434 v0.6 for game v1.21+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	sneby-Thermal Devices-2518984513 v1.1 for game v1.19+
		Currently ACTIVE

	sneby-Liquidentifier Reskin-2521645131 v1.0 for game v1.19+
		Currently ACTIVE

	Bangee-Cosmic map-local v1.0 for game v1.14+
		Currently ACTIVE
		Has been initialised

	PersonMan65-Injectable Flasks Mod-local v1.0 for game v1.19
		Currently ACTIVE

	jimmyl-Liquid-related Machinery-2550340103 v0.6 for game v1.19+
		Currently ACTIVE

	CrocblancYT-Extra Machinery-2555203773 v1.2.5 for game v1.11
		Currently inactive

	Orsoniks-A Crap Ton Of Damage-2603531653 v0.1 for game v1.21.3
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently ACTIVE

	sneby-Hydraulic Pistons-2636571776 v1.0 for game v1.21.3+
		Currently ACTIVE

	PeppRRicoochie-The Grappling Gun Mod-2637017257 v2.1 for game v1.22.3
		Currently ACTIVE

	pjstarr12-Customizable Gun Mod-local v1.0 for game v1.21+
		Currently ACTIVE

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently ACTIVE

	Squidboy82-Test Entity-local v1.0 for game v1.15
		Currently ACTIVE

	Ghost Turtle-Tornado Mod V1.0-2666039457 v1.0 for game v1.22.2
		Currently ACTIVE

	Matyfou-Firecrackers-2666846595 v1.1 for game v1.12.2+
		Currently ACTIVE

	Timtam-Creatures Mod-2721001484 v1.0 for game v1.21+
		Currently ACTIVE

	Dawid23 Gamer-Dawid23 Gamer's Chemistry Mod-2721981192 vv1.1.0 for game v1.23.7+
		Currently ACTIVE

	Senpai-i-i...-Traumatic Gun-2730106495 v1.0 for game vAny
		Currently ACTIVE

	01 Studios-Human Dynamic Emotions-2745225441 v1.0 for game v1.22+
		Currently ACTIVE

	Dyadyushka Dyadya-Acid Sea (FIXED)-2759438689 v1.0 for game v1.24+
		Currently ACTIVE
		Has been initialised

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently ACTIVE

	Skittles-Guns 'N Ammo-2761082698 v1.0 for game vwhatever is the latest
		Currently ACTIVE

	Bobr-Melon Playground-2765846309 v1.1 for game v1.50+
		Currently ACTIVE

	Aspa102-OCM (By subscribing you accept that the mod is broken and you shouldn't even have it)-local v2.0 for game v1.21
		Currently inactive
		Malfunctioning

	Dyadyushka Dyadya-SpawnableLift-2780861030 v1.0 for game v1.23+
		Currently ACTIVE
		Has been initialised

	Brian9171, Purepsi-Gears-local v1.0 for game v1.23+
		Currently ACTIVE

	Decibek-Crash Test Dummy-local v1.0 for game vany version
		Currently ACTIVE

	Frosty-Accurate Resize & Position-2789547018 v1.0 for game v1.23
		Currently ACTIVE

	Morzzic-Water Physics-2793815479 v1.1 for game v1.23+
		Currently ACTIVE

	Mishanya-The Ultimate Car Mod-local v0.5 for game v1.16+
		Currently ACTIVE

	Mishanya-The Ultimate Car Mod-local v0.5 for game v1.16+
		Currently ACTIVE

	Snark555-Liquid Lava mod-2799410334 v1.0 for game v1.23.10
		Currently ACTIVE

	Sohvaperuna-Limb Reattachment Tools-2801931724 v3.2.6 for game v1.24+
		Currently ACTIVE

	Orsoniks/Navii-Husk Overdose-local v1.0 for game v1.21+
		Currently ACTIVE

	JohnnyTaco-PP-NPC-2803192317 v0.02 for game v1.22.x
		Currently ACTIVE

	zuccian-Symbiote Playground-2803459361 v1 for game v1.10+
		Currently ACTIVE

	pjstarr12-Map Colorizer-2804670179 v1.0 for game v1.23+
		Currently ACTIVE

	Orsoniks/Navii-Anti-Gravity Device-local v1.0 for game v1.23+
		Currently ACTIVE

	zuccian-ZOOM-2810253651 v1.0 for game v1.10+
		Currently ACTIVE

	Prototrode-Powerful Generators-2811445505 v1.2 for game v1.25+
		Currently ACTIVE

	Byter28-Gas Burner-2811763416 v1.0 for game vany
		Currently ACTIVE

	catt0215-Catt's Cannons-2814325736 v5.5 for game v1.25+
		Currently ACTIVE

	JulianMagicCraft-JMC's Technology and Chemistry-2815242030 v1.3.1 for game v1.14+
		Currently ACTIVE

	Brian9171-Limb Attachments-2660556899 v0.3 for game v1.22+
		Currently ACTIVE

	gwenenenen-More Guns-2235585600 v1.0 for game v1.10.2
		Currently ACTIVE

	Decibek-City-local v1.0 for game v1.14+
		Currently ACTIVE
		Has been initialised

	FredMichalBear-Furry defenders mod-local v1.0 for game v1.16+
		Currently inactive

	FredMichalBear-Furry defenders mod-local v1.0 for game v1.16+
		Currently inactive

	Prussian Doge-Furries-2834007979 v1.1 for game v1.24+
		Currently inactive

	666dtoxzik // defa1t-Underground Complex-2834190786 v1.0 for game v1.24-1.25+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Dead creatures remover button-2838002082 v1.0 for game v1.24+
		Currently ACTIVE

	Mishanya-Functional Helicopter Mod-local v0.3 for game v1.25+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Fire remover button-2840340693 v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Unlimited Camera Zoom-2843793869 v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Environment time changer-2850737647 v1.0 for game v1.24+
		Currently ACTIVE

	ibiglaser-Abyss corruption system-2853132719 v2.0 for game v1.25+ and Dyadyushka Dyadya
		Currently inactive

	Morzzic-Deformation Mod-2856121663 v1.0 for game v1.25+
		Currently inactive

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.22+
		Currently ACTIVE
		Has been initialised

	Noahzjones-SubHybrid-2857910815 v1.0 for game v1.14+
		Currently ACTIVE
		Has been initialised

	DreamingWarlord-PBullets-2858824981 v1.0 for game v1.25.4
		Currently ACTIVE

	игор-Bomb Tech-2863195081 v1.0 for game v1.14+
		Currently ACTIVE

	ibiglaser-Make Anything Invisible-2864708184 v1.0 for game v1.25+
		Currently ACTIVE

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	zuccian-Better Gore-2871465069 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Void-Void's Modular Weapon Pack (VMWP)-2875194054 v0.5 for game v1.24+
		Currently ACTIVE

	Laska, Webber, Fludih-Dobromol, Quickness-Prostheses-2882002619 v1.0 for game v1.21+
		Currently ACTIVE
		Has been initialised

	SHkolodron'ka-Black Hole Sticky Grenade-2882974405 v0.1 for game v1.21+
		Currently ACTIVE

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	Dyadyushka Dyadya-Antigravity Map-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	weirdo-Advanced Damage-2212880187 v2.1 for game v1.22.2+
		Currently inactive

	Azule-Aerodynamics-2798194010 v1 for game v1.23.x+
		Currently inactive

	Dyadyushka Dyadya-Arrows and crystals are now debris-local v1.0 for game v1.24+
		Currently ACTIVE

	Kor_BarBeQ-Ballistic Playground-local v1.0 for game v1.25+
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	01 Studios-Human Dynamic Emotions-2745225441 v1.0 for game v1.22+
		Currently ACTIVE

	Morzzic-Object Editor-2590195142 v1.2 for game v1.17+
		Currently ACTIVE

	Quickness-More Vehicles-2805966221 v1.4 for game v1.24
		Currently ACTIVE

	Digito-Operation LSA Forces: MARSOC (MAROSC UPDATE AND GENERAL APOLOGY)-2824743154 v1 for game v1.20
		Currently inactive

	Свинка Панамка-Pablo's Weapons-2205927503 v1.0 for game v1.8.1
		Currently ACTIVE

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive
		Malfunctioning

	JohnnyTaco-PP-NPC-2803192317 v0.02 for game v1.22.x
		Currently ACTIVE

	JohnnyTaco-Puppet Master-2668334393 v1.70.7 for game v1.22.x
		Currently ACTIVE
		Has been initialised

	yksus152-Random Tactical Guns /HD/-2827278412 v1.0 for game v14.88
		Currently ACTIVE

	yksus152-Random Tactical Guns /HD/ 2-local v1.0 for game v1.14+
		Currently inactive

	yksus152-Random Tactical Guns /HD/ 3-local v1.0 for game v1.14+
		Currently ACTIVE

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently ACTIVE

	Zkryhngro�meister-Science Hazard Minus-2691553761 v1.8 for game v1.24.6+
		Currently ACTIVE

	Pumpkin-Simple Syringes Mod-2522356867 v2.2 for game v1.18+
		Currently ACTIVE

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently ACTIVE

	cheems-Bob Mod-2825346106 v1.1 for game v1.24.X
		Currently ACTIVE

	Aubarino (yeeteeyt helped)-The Sex Mod-local v1.0 for game v1.23+
		Currently ACTIVE
Don't ask lol I'm developing this mod
	Kyrelink and Quickness-The ULTIMATE Minecraft Mod-2442812460 v1.8 for game v1.23+
		Currently inactive

### Additional notes

Hello!

**Comment by yeeteeyt** [comment] 2022-12-08 02:21
OH! one last issue. Procedural gore doesn't seem to differentiate between body parts. I can get ribs from someone's leg and stuff like that. maybe it's just me

**Comment by PossiblyRemember** [comment] 2022-12-08 22:22
This is [Zuccians Better Gore Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2871465069), not the game. If you are having issues with this mod, go post a comment on their workshop page. For the other problems that are seemingly in the actual game, make sure you disable all mods and check if the bug still occurs, then post them as different issues as to not multirequest.

**Comment by mestiez** [comment] 2022-12-08 23:13
I'm really not sure what to do with this issue since it groups many things, half of which caused by 1 mod. I guess I'll close it unitl these bugs are properly, individually reported or until I get a better idea lol

**Closed by mestiez** 2022-12-08 23:13 UTC
Labels: bug
