### ISSUE TITLE
Land Break

### ISSUE THREAD

**Issue by isavailablh** [studio-minus/ppg-bugs-and-requests#166] opened 2021-09-01 03:23 UTC
**Describe the bug**
Land breaking

**Clearly describe how to reproduce the bug**
place something and cause a giant glitch which for me usually breaks the land

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: Windows 10 Pro
 - Game version: most recent as of 8/31/2021
 - GPU: GeForce GTX 3070
 - CPU: Intel Core i9 10th gen

**Additional notes**
![image](https://user-images.githubusercontent.com/85230353/131606594-94cb4d6b-f392-4879-8c70-caa409525480.png)
demonstration of the look when it happens. IDK if it can be properly reproduced, but it happens.

**Comment by mestiez** [comment] 2021-09-01 11:02
Duplicate of #1

**Closed by mestiez** 2021-09-01 11:02 UTC
Labels: bug
