### ISSUE TITLE
Corrupted saves

### ISSUE THREAD

**Issue by Jawrek** [studio-minus/ppg-bugs-and-requests#852] opened 2022-03-16 17:34 UTC
Hi, so whenever I open up the beta version of the new update and join a game, I try to spawn certain items from my saves into the game, yet for a lot of the saves, mine and from the workshop, it says they are corrupted. I understand the early stages of the update, yet I am unsure if this problem has been bought up. I'm also unsure to what could be triggering the corruptions as its not for all of the saves

**Comment by AlexCodeMan** [comment] 2022-03-16 17:51
Oh, about me, too, an open topic with this problem. Even the Tungsten mod disappeared.... And the saves flew.

**Comment by mestiez** [comment] 2022-03-16 18:37
Duplicate of #841

**Closed by mestiez** 2022-03-16 18:37 UTC
Labels: bug
