### ISSUE TITLE
More convenient recompilation of mods

### ISSUE THREAD

**Issue by Chagarock** [studio-minus/ppg-bugs-and-requests#1957] opened 2022-08-11 11:57 UTC
**Feature description**
When you press the "ESC" key in the game, a menu opens where you can select "Settings", "Exit", etc. I suggest adding the "Mods" button there as well, when pressed, a list of installed mods opens with the ability to recompile any of them. And also, if possible, the button at the very top, where the "Disable all" and "Enable all" buttons are located, the "Recompile all" button.

**Feature purpose**
Currently, PPG only allows you to recompile a mod when it has an error and only in the main menu of the game. And if the mod did not give an error, but something needs to be corrected in it, you have to restart the game so that it is recompiled again. Because of this, a lot of time is lost and the desire to work on the mod quickly disappears.
**If you add this, it will make modding incredibly easy!**

**Comment by DindinYT37** [comment] 2022-08-11 12:06
Duplicate of or Related to:
* #589
* #605 
* #694
* #1072 
* #1173 
* #1192 
* #1794 

*Note that basically what you requested here was rejected several times before, so this will probably also be rejected.*

**Closed** 2022-08-11 12:09 UTC
Labels: feature-request
