### ISSUE TITLE
Blood Types

### ISSUE THREAD

**Issue by PhantomKobra** [studio-minus/ppg-bugs-and-requests#1981] opened 2022-08-17 06:39 UTC
**Feature description**
Each human spawns with a random blood type that can be changed in the selection menu, if you give a human with a low amount of blood the wrong blood type, they die.

**Feature purpose**
Realism. It would make for a good medical scene, as doctors don't just pull random patients out of the waiting room for blood transfusions. They need specific types that are capatible with the donor's own bloodtype.

**Additional context**
Nah.

**Comment by DindinYT37** [comment] 2022-08-17 06:41
Duplicate of or Related to:
* #697
* #746

Try checking for the Duplicates *before* opening instead of after next time

**Closed** 2022-08-17 06:41 UTC
Labels: feature-request
