### ISSUE TITLE
Prosthetic Limbs

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#425] opened 2021-11-03 22:52 UTC
**Feature description**
A plastic/metal leg or arm that automatically snaps to a missing limb.

**Feature purpose**
It would be cool for building a hospital, curing a human, and various other creative things.

**Additional context**
Nothing else

**Comment by Afavertov** [comment] 2021-11-03 23:48
Made it by yourself.

**Comment by Cboyjet4** [comment] 2021-11-04 00:14
> Made it by yourself.

???????????????????????????

Also, duplicate of #254 https://github.com/studio-minus/ppg-bugs-and-requests/issues/254

**Comment by bluewoods64** [comment] 2021-11-04 02:45
> Made it by yourself.

wdym make it by myself? i can't code. this is literally a feature request page, i am requesting a useful feature.

**Comment by bluewoods64** [comment] 2021-11-04 02:46
> > Made it by yourself.
> 
> ???????????????????????????
> 
> Also, duplicate of #254

well it seems like zooi didnt notice it so i'll just say it again

**Comment by mestiez** [comment] 2021-11-04 23:24
> > > Made it by yourself.
> > 
> > 
> > ???????????????????????????
> > Also, duplicate of #254
> 
> well it seems like zooi didnt notice it so i'll just say it again

That isn't how the issue board works. There shouldn't be any duplicates, whether you think I noticed or not.

**Closed by mestiez** 2021-11-04 23:24 UTC
Labels: feature-request
