### ISSUE TITLE
No Uploud button

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#347] opened 2021-10-29 23:56 UTC
**Describe the bug**
I wanted to export the mod to the workshop, but I can't, because there is no Uploud button. 

**Clearly describe how to reproduce the bug**
no steps

**Mod list**
only mine

**System info (please complete the following information)**
Operating system: Windows 10
Game version: 1.22 beta (64 bit)
GPU: NVIDIA Geforce GTX 1050 ti
CPU: intel core i3-7100 (4)

**Additional notes**
![Скриншот 30-10-2021 095521](https://user-images.githubusercontent.com/69407926/139512473-28304779-f05b-496c-8a94-25933d89d7fd.jpg)

**Comment by mestiez** [comment] 2021-10-30 10:45
This is not a bug. The mod you are trying to upload has been marked as "owned by someone else". This means that you probably used some other mod as a template or foundation. You can resolve this by deleting any UGC related fields in the `mod.json` of your mod.

**Closed by mestiez** 2021-10-30 10:45 UTC
Labels: bug

**Comment by Quickness19** [comment] 2021-10-30 10:56
![image](https://user-images.githubusercontent.com/69407926/139530111-57a9cbfc-6fde-45f2-865d-88157050dd8c.png)
