### ISSUE TITLE
Wind for Environment Settings

### ISSUE THREAD

**Issue by GithubPerson2021** [studio-minus/ppg-bugs-and-requests#1744] opened 2022-07-14 22:03 UTC
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?
Wind is a mechanic that could be added in a new map or as a environment setting. Basically it pushes objects with the wind speed chosen. Wind angle and speed can be changed inside environment settings.

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?
The purpose of wind is to make the game feel more realistic and less dull. I saw a link on discord for this so i decided to add this.
**Additional context**

**Comment by fhgb54643689** [comment] 2022-07-14 22:07
use the template

**Comment by DindinYT37** [comment] 2022-07-14 22:54
Similar or Duplicate of:
* #1610 
* #1014
* #997 
* #184

**Closed** 2022-12-31 02:30 UTC
Labels: feature-request

**Comment by Drogo-man** [comment] 2023-01-01 12:10
hmm
