### ISSUE TITLE
Layering presistence when saving/loading

### ISSUE THREAD

**Issue by RoofRioter** [studio-minus/ppg-bugs-and-requests#1515] opened 2022-06-21 16:42 UTC
**Feature description**
New Feature

**Feature purpose**
This Also A Bug But Its Gonna Be Feature Suggestion Instead. So I Made A Metal Barrel Out Of Re-sizable Housing And When i Saved It The Grey main part of the barrel* over laps the outer part. What I Think Would Be Cool Like power point would be like if you could force an item to overlap or go behind an item, Problem Mainly Exists When Saving.

*the middle part, not the metal rims

**Additional context**
![image](https://user-images.githubusercontent.com/107360217/174853181-27bf877f-bf97-4fc8-89d8-0c4f24dbd804.png)

**Comment by DindinYT37** [comment] 2022-06-21 16:52
This is a bug report, if this were a feature request it would be a duplicate of #838.

**Comment by RoofRioter** [comment] 2022-06-21 17:02
oh ok

**Closed** 2022-12-31 02:26 UTC
Labels: feature-request
