### ISSUE TITLE
pickaxe

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2072] opened 2022-09-03 08:42 UTC
**Feature description**
a heavy pickaxe that can impale on both sides

**Feature purpose**
for smashing rocks, or heads, whatever

**Additional context**
![image](https://user-images.githubusercontent.com/109692890/188263167-1a5d9599-751b-403c-ab3b-4225cfa2c8e8.png)

**Comment by DindinYT37** [comment] 2022-09-03 10:33
Duplicate of or Related to:
* #657
* #1145

**Closed** 2022-09-03 17:50 UTC
Labels: feature-request
