### ISSUE TITLE
Resizing both sides of an object independantly

### ISSUE THREAD

**Issue by kpp4** [studio-minus/ppg-bugs-and-requests#1996] opened 2022-08-20 20:34 UTC
**Feature description**
Being able to resize either side of an object, instead of a single x and z axis line, you should have 2 of them on each side (up, down, left, right)

**Feature purpose**
To make building easier

**Additional context**
Its surprising no one has done this yet :/

**Comment by awaheartemoji** [comment] 2022-08-21 13:52
Probably a duplicate of #540

**Comment by DindinYT37** [comment] 2022-08-21 13:56
Duplicate of or Related to:
* #540 
* #1088 
* #1434

**Closed** 2022-08-31 12:16 UTC
Labels: feature-request
