### ISSUE TITLE
better androids

### ISSUE THREAD

**Issue by hdfjsh** [studio-minus/ppg-bugs-and-requests#2113] opened 2022-09-07 10:52 UTC
**Feature description**
when androids get something heavy thrown at them it can make a dent in the android
**Feature purpose**
for fun!

**Additional context**
nope

**Comment by DindinYT37** [comment] 2022-09-07 11:24
Duplicate of or Related to:
* #655
* #659
* #1222 
* #1440 
* #1872 
* [<img src="https://user-images.githubusercontent.com/64973205/188866153-7e79e286-903c-4cbf-bcb7-8e82e8460a04.png" width="16px" height="16px"> **"[MOD] Deformation"](https://steamcommunity.com/sharedfiles/filedetails/?id=2856121663)

Also, please use a more descriptive title and explain your request more detailed.

**Comment by hdfjsh** [comment] 2022-09-07 17:59
thanks dude

**Comment by royalealbert27** [comment] 2022-09-14 12:31
it can already damage the android if you throw something heavy at them really fast

**Closed** 2022-09-15 23:01 UTC
Labels: feature-request
