### ISSUE TITLE
Red Life Syringe

### ISSUE THREAD

**Issue by BugMan33** [studio-minus/ppg-bugs-and-requests#535] opened 2021-11-22 12:55 UTC
**Describe the bug**
Yesterday everything was fine . Today I played People Playground and I found a bug, when you spawn life syringe it is red . Only Life syringe is affected idk what happend.

**Clearly describe how to reproduce the bug**
Spawn life syringe

**Mod list**
Only mods that affected the syringes are A Handful of Wierd Syringes and Raw Pink Liquids

**System info (please complete the following information)**
 - Operating system: Windows 10 pro
 - Game version: 1.22.2
 - GPU: amd radeon rx 5500m
 - CPU: amd ryzen 4800h

**Additional notes**
I also found plenty of bugs in the Quick Right Click Options with the new 1.22 update.
![syringe](https://user-images.githubusercontent.com/89192183/142865398-d19f940f-e5cb-4303-a95f-479fef1b6da6.png)

**Comment by DindinYT37** [comment] 2021-11-22 21:17
@BugMan33, you're supposed to give the **full** mod list because there may be mods you didn't know are affecting Syringes. Also your additional note, that a **mod** has a lot of bugs makes no sense. If you really care about those bugs report it to the mod maker.
*Note: I am not trying to take @mestiez's place by telling you all this, I am just telling you this in general so you can make better bug reports in the future.*

@mestiez, it seems like the Life Syringe has turned into the color of Blood, probably because it's the Standard Color or maybe because of a spelling error. (Wrong variable used etc.)

**Comment by mestiez** [comment] 2021-11-23 19:25
I do not have this issue and can't reproduce it without purposefully draining the life syringe and filling it with blood...

**Comment by mestiez** [comment] 2021-11-23 19:26
I will close this issue until @BugMan33 provides their full list of mods.

**Comment by DindinYT37** [comment] 2021-11-23 19:27
> I will close this issue until @BugMan33 provides their full list of mods.

It happens for me too, I can share my modlist.

**Comment by mestiez** [comment] 2021-11-23 20:07
that is an unreasonably long list, this will take forever

**Comment by mestiez** [comment] 2021-11-23 20:08
This is most certainly caused by a mod but I don't know how or what mod causes it

**Comment by DindinYT37** [comment] 2021-11-23 20:10
> that is an unreasonably long list, this will take forever

Indeed I have many mods

**Comment by CoalSephos** [comment] 2021-11-24 03:12
Noticed the same issue, I think the mod conflict is
```
Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
	Currently ACTIVE
```
This is the mod that we both share and disabling/enabling toggles this red life syringe issue.

**Comment by mestiez** [comment] 2021-11-24 16:05
Thanks for finding the cause of the problem!

**Closed by mestiez** 2021-11-24 16:05 UTC
Labels: bug, unclear
